docs/index.rst, docs/style-guide.rst
Here's what I have so far to address #744. I'm running into a strange issue where lines in code blocks that *should* line up don't, as though some half-width character shenanigans are going on. Does anyone know if this is a Sphinx issue or if I just formatted the code blocks incorrectly? It seems hypocritical to assert that `let` blocks should be vertically aligned, only to have them shown out of alignment a few pixels below that very sentence.
I'll squash everything down once the PR looks good to merge.
=> Migrate hylang/hy-style-guide to Hy Documentation

docs/tutorial.rst
1. It was mistyped as lisP comprehensions instead of lisT comprehensions (Unless it was intended as a pun :wink:)
> ~~2. Function was defined as `optional-arg` but used as `optional_arg`~~
Reverted this change after discussions with @theanalyst and @berkerpeksag
=> Fix typos in tutorial docs

AUTHORS, hy/cmdline.py, hy/errors.py, hy/importer.py
Previously, Hy scripts that raised a subclass of IOError would be caught by code intended to deal with IOErrors raised when Hy couldn't import the script itself, resulting in either a misleading "Can't open file" error message, or a misleading TypeError traceback from not being able to format the "Can't open file" message (for IOErrors for which the errno attribute was None). This commit (a straightforward implementation of the idea proposed by @slimetree in #714) introduces a new HyIOError class, raises that when `import_file_to_hst` can't open the file path, and catches it in the `cmdline_handler`.
Tested manually against Python 3.4.0. This is believed to fix #513, #714, and #727.
=> improve traceback legibility by means of distinguishing source of IOErrors

hy/compiler.py, hy/completer.py, tests/compilers/test_compiler.py, tests/test_bin.py
jcrocholl/pep8 (used by flake8, used in Hy's continuous integration builds) introduced an imports-at-top-of-file check in 1.6.0 and a line-breaks-around-binary-operators check in 1.6.2. This commit makes nonfunctional changes to bring the Hy codebase in compliance with this tool, and should fix #764.
(Alternatively, if the way things were is judged superior, it would surely be possible to configure pep8/flake8 to ignore the specific unwanted warnings.)
=> move imports and operators to satisfy new version of pep8 checker

hy/_compat.py, hy/compiler.py, setup.py, tests/native_tests/mathematics.hy
*Conditional* on berkerpeksag/astor#17&mdash;
Python 3.5 will have a new commercial-at infix operator with the magic
methods \_\_matmul\_\_, \_\_rmatmul\_\_, and \_\_imatmul\_\_, unused as yet in the
standard library, but intended to represent matrix multiplication in
numerical code; see PEP 465 (https://www.python.org/dev/peps/pep-0465/)
for details. This commit (developed against Python 3.5 alpha 3) brings
support for this operator to Hy when running under Python 3.5 (or,
hypothetically as yet, greater). For Hy under Python <= 3.4, attempting
to use `@` in function-call position currently results in a NameError;
this commit does not change that behavior.
This is intended to resolve #668.
=> add support for Python 3.5 infix matrix multiplication

.travis.yml, Makefile
Using travis' container based infra which is faster & allows caching pip
and is faster, also after the environment update hy seems happy with
pypy2.5 so removing the hacks needed to pass that.
=> travis: run in container infra & remove pypy hacks

hy/compiler.py, tests/native_tests/language.hy
As reported in issue #748, there was a bug in which passing a lambda as the value of a :keyword argument would fail—
```
$ hy --spy
hy 0.10.1 using CPython(default) 3.4.0 on Linux
=> (sorted (range 10) :key (fn [x] (- x)))
from hy.core.language import range
sorted(range(10), key=_hy_anon_fn_1)
File "<input>", line 1, in <module>
NameError: name '_hy_anon_fn_1' is not defined
```
The function call would appear in the generated AST without being preceded by the appropriate function definition corresponding to the anonymous function argument value in the Hy source, causing either a NameError (as in the example above), or erroneous reuse of whatever function was already pointed to by the `_hy_anon_fn_` name referenced in the list of keywords passed to …
=> Can use lambdas with :keyword argument passing

NEWS
At time of writing, the last comment on the Release 0.10.2 issue #709 is from our Benevolent Dictator For Life @paultag, who writes, 
> Can someone send up a NEWS? We're good to release once that's in master.
This pull request contains a preliminary draft of such a release entry with a summary of changes from 0.10.1 (compiled from scrolling up through gitk from the 0.10.1 tag, looking up the pull requests from merges, and composing bullet points for anything that seemed interesting) for subsequent editing by Hy Society prior to the release.
=> preliminary draft of NEWS for 0.10.2

docs/language/api.rst, hy/compiler.py, tests/native_tests/language.hy
Proof of concept for #809. I need this for a Hy-only nREPL implementation.
=> Allow specification of global table and module name for (eval ...)

docs/language/api.rst
Also adds an example illustrating this behaviour.
=> Documents (left-to-right) order of variable assignments in let expressions

hy/core/macros.hy, tests/native_tests/native_macros.hy
Now you can do stuff like
```
(defn main []
(print "Hy!"))
(defmain [&rest foo]
(main))
```
without infinite recursion.
=> Make (defmain ...) a clean macro

CONTRIBUTING.rst, README.md
Include the text of the Contributor Covenant (1.1.0) in CONTRIBUTING.rst, and add a link to the document to README.md.
=> Adopt a Code of Conduct

docs/language/api.rst
svetlyak40wt mentioned on IRC that the documentation for keyword args is not exactly up to speed.
=> Expand doc for defn with &kwargs

hy/contrib/walk.hy, tests/native_tests/contrib/walk.hy
Expressions can sometimes contain itertools.islice objects, which we can only walk if we force them into a list. To do this, the walk function has to be taught that collections that are not instances of list should be forced into a list.
=> contrib.walk: Coerce non-list iterables into list form

hy/compiler.py, tests/native_tests/language.hy
Approximately seven hours ago, some AST changes [landed in Python](https://hg.python.org/cpython/rev/a65f685ba8c0) that had some alarming consequences for Hy's behavior, consequences such as this—
```
$ nosetests
..............E..E....E.........E............E......F....F.E...E.........E..E.......................................F............................F..EE..........FF.......................1
.................F.........................
...F..................F..................................................................................................................................FF..FF.
[failure details redacted ...]
Ran 388 tests in 44.353s
FAILED (errors=11, failures=13)
```
—and this—
```
hy 0.10.1 using CPython(default) 3.5.0a4+ on Linux
=> (defn all-the-args [&rest args …
```
=> prevent PEP 448 from breaking the world

hy/importer.py, hy/macros.py, hy/models/__init__.py, hy/models/complex.py, hy/models/cons.py, hy/models/dict.py, hy/models/expression.py, hy/models/float.py, hy/models/integer.py, hy/models/list.py, hy/models/string.py, hy/models/symbol.py, tests/models/test_replace_hy_obj.py, tests/models/test_wrap_value.py
Currently '.replace' method is used to replace hy objects. This is not
safe when we are not sure if the 'obj' in 'obj.replace(other)' is an
instance of HyObject.
In these cases, we can use function 'replace_hy_obj(obj, other)'
instead. This function will try to wrap 'obj' if it's not an instance of
HyObject.
This also means that we need a wrapping function in hy.models'. Hence I
moved the '_wrap_value' function from hy.macros into hy.models. To avoid
circular importing, the wrapper functions are provided individually by
each model type's own file.
=> Add 'replace_hy_obj' to safely replace Hy objects

docs/language/api.rst, hy/compiler.py, tests/compilers/test_ast.py, tests/native_tests/py3_only_tests.hy
I'll be honest; I'm kind of ashamed that this patch for #453 is the result of crude reasoning-by-analogy to how `&optional` is implemented and experimental observations tinkering with `inspect.getfullargspec` and `compile( ... , ast.PyCF_ONLY_AST)`, rather than a deep, crystal-clear understanding of the theory and implementation of Hy and Python's AST.
On the other hand, it seems to actually work&mdash;
```
(hy) zmd@ExpectedReturn:~/Code/hy/hy$ hy --spy
hy 0.10.1 using CPython(default) 3.4.0 on Linux
=> (defn example [a &kwonly b [c nil]]
...   (print a b c))
def example(a, *, b, c=None):
return print(a, b, c)
=> (example 1 :b 2 :c 3)
example(1, b=2, c=3)
1 2 3
=> (example 1 :b 2)
example(1, b=2)
1 2 None
=> (example 1)
example(1)
File "<input>", line 1, …
```
=> keyword-only arguments

AUTHORS, docs/contrib/anaphoric.rst, hy/contrib/anaphoric.hy, tests/native_tests/contrib/anaphoric.hy
In relation to #787
`ap-pipe` is an anaphoric version of `->` and `->>`. It is useful for specifying where the argument should go in each expression.
```hy
(ap-pipe 3 (+ it 1) (/ 5 it))
=> 1.25
(ap-pipe [4 5 6 7] (list (rest it)) (len it))
=> 3
```
`ap-compose` returns a function which is the composition of several anaphoric forms.
```hy
(def op (ap-compose (+ it 1) (* it 3)))
(op 2)
=> 9
```
=> Added ap-pipe and ap-compose macros

docs/language/api.rst, hy/core/macros.hy, hy/macros.py, tests/native_tests/reader_macros.hy
The `with-decorator` special form is not the most ergonomic—this commit
introduces a new builtin `#@` reader macro that expands to an invocation
of `with-decorator`. To support this, `reader_macroexpand` is made to
also look in the default `None` namespace, in imitation of how
regular (non-reader) macros defined in hy.core are looked up. The
docstring of `hy.macros.reader` is also edited slightly for accuracy.
This in the matter of issue #856.
=> reader macro #@ for with-decorator

hy/lex/__init__.py
This repairs things like the following:
(import [hy.lex [tokenize]])
(tokenize "(foo))")
Without this patch, the lexer exception thrown by `tokenize` is unprintable because of the missing source reference.
=> Explicitly set missing source on LexExceptions

hy/compiler.py, tests/native_tests/language.hy
This basically wraps statements into a function call. It *only* wraps statements, so `(and 1 1)` will still be compiled to just `1 and 1`.
Closes #233 and #766.
=> Make and/or short-circuit

docs/language/api.rst, docs/tutorial.rst, hy/compiler.py, tests/native_tests/contrib/meth.hy, tests/native_tests/defclass.hy, tests/native_tests/mathematics.hy, tests/native_tests/with_decorator.hy, tests/native_tests/with_test.hy
defclass now has a new syntax:
```hy
(defclass Name [BaseList]
"Optional docstring"
[property value
property value] ;; optional
(defn method [self]
self.property))
```
Anything after the optional property list (which will be translated to a setv within the class context) will be added to the class body. This allows one to have side effects and complex expressions within the class definition.
As a side effect, defining methods is much more friendly now!
Closes #850.
=> defclass reimagined

hy/lex/parser.py, tests/lex/test_lex.py
Postfixing functions with a bang, like set!, get!, etc are relatively
common. However, those names are not valid in python, so in the name of
python interoperability, lets mangle them to set_bang and get_bang,
respectively.
Closes #536.
=> Mangle trailing bangs on symbols

hy/compiler.py, tests/compilers/test_ast.py
When trying to setv a callable, raise an error instead of showing the
user an incredibly ugly backtrace. Closes #532.
=> Trying to setv a callable should raise a nice error

hy/compiler.py, tests/compilers/test_ast.py
Some valid-looking list comprehensions, such as (genexpr x []) can crash
Python 2.7. The AST we generate from these cannot be expressed in
Python, but were valid in Hy.
Added two guards to guard against this, so we raise an error instead of
crashing Python.
Closes #572, #591 and #634.
=> Guard against a few invalid list comprehension cases

docs/contrib/anaphoric.rst, hy/contrib/anaphoric.hy, tests/native_tests/contrib/anaphoric.hy
These work like Clojure's `#()` anonymous function literals, and were discussed at length in #879.
`(xi foo x1 x2 xi)` in Hy is now analogous to `#(foo %1 %2 %&)` in Clojure. I appended it to `anaphoric.hy`, so you must `require` it to use `xi`.
=> added xi-forms

docs/contrib/anaphoric.rst, hy/contrib/anaphoric.hy, tests/native_tests/contrib/anaphoric.hy
I just realized something.
```Clojure
user=> (def foo #(% 2 3))
#'user/foo
user=> (foo +)
5
user=> (foo -)
-1
user=> (foo /)
2/3
```
The parameter can appear in the function position.
This won't currently work in Hy's xi forms because the first element isn't checked for xi symbols, but I just fixed that with this slight adjustment.
=> xi parameter may appear in function position

hy/compiler.py, hy/importer.py, tests/native_tests/language.hy
Typecheck `eval` arguments during execution instead of compilation
When checking types during compilation, things like
(eval '(print 1) (. foo mod))
fail, even if `(. foo mod)` is a dictionary.
=> Eval args typecheck

hy/compiler.py, tests/native_tests/language.hy
To mirror the behaviour of (setv), allow an empty (del) too: one that
shall return nil. Closes #905.
=> Allow (del) without arguments

hy/core/macros.hy, tests/native_tests/language.hy
For easier macro writing purposes, allow an empty (cond), that simply
returns nil. Closes #904.
=> Allow an empty (cond)

hy/compiler.py, tests/compilers/test_ast.py
To allow classes to have methods that match built-in names, yet, still
disallow them outside of defclass, keep an internal state whether
builtins are allowed in the current context.
By default, this is false. But defclass will set it to True when it
compiles its body, and set it back to the previous value when it's done
with that. We need to set back to the previous value to allow nested
defclasses to work properly.
This closes #783.
=> Allow defclass to have properties/method with built-in names

hy/macros.py, tests/macros/test_macro_processor.py
This PR makes the MacroExpansionErrors cleaner when the source of the error is invalid arguments. Unfortunately, python just raises TypeErrors, and I don't see an easy way to distinguish TypeErrors raised by an invalid number of arguments, from other sources. So, this PR creates an empty lambda with the same signature as the anonymous macro function, and calls that. Any TypeError must be the result of invalid arguments.
Before:
=> (let)
File "<input>", line 1, column 1
(let)
^---^
HyMacroExpansionError: expanding `let': TypeError("_hy_anon_fn_3() missing 1 required positional argument: 'variables'",)
After:
=> (let)
File "<input>", line 1, column 1
(let)
^---^
HyMacroExpansionError: expanding `let': missing 1 required positional argument: 'variables'
=> Better error messages on invalid macro arguments

docs/language/core.rst
I've added a section for the (keyword?) function, as raised in bug #730
=> Added documentation for the (keyword?) function

hy/compiler.py, tests/native_tests/language.hy
Currently some of errors for built-in forms make references to a particular one of the multiple they handle. This can be confusing, for example, attempting to compile `(def foo bar baz)` produces:
HyTypeError: setv needs an even number of arguments
This one and `fn/lambda` are the two I see. Please let me know if anyone can find any others and I'll add them to this pr.
=> Remove hard-coded references to 'fn' and 'setv' in errors

docs/language/api.rst, hy/models/integer.py, tests/native_tests/language.hy
This allows us to parse things like 0xDEADBEEF or 0o080.
Filed as issue #937
=> Add hex and octel support to Hy integers

.coveragerc
On 21 September, all the continuous integration checks on a revision of
pull-request #920 were observed to fail with a "CoverageException:
Unrecognized option '[run] exclude_lines=' in config file
.coveragerc". One can only imagine that this was due to it trying to use
the new version 4.0 of Ned Batchelder's ever-popular coverage.py (just
released on 20 September), with which our existing .coveragerc may not
be compatible. Unfortunately, a quick glance at the documentation was
not sufficient for the present author to deduce how we should edit our
configuration to be in compliance with the new version of the tool; as a
temporary workaround to get the CI Hy infrastructure up and running,
this pull request proposes an attempt to pin us to the just-prior version of coverage.
=> fix CI by downgrading Coverage?

README.md
Ref #940, #942, #945.
The language cleanup is confusing the new people. This is at least the third time someone has complained that `defclass` is broken.
=> Add link to stable docs

hy/compiler.py, tests/native_tests/defclass.hy
When using `defclass`, having to remember to explicitly return `nil` from `--init--` is painful. Ideally, `--init--` should do that automatically.
There are, unfortunately, a number of ways to define an `--init--` function:
```hy
(defclass Something []
[--init-- (fn [self] ...)])
```
```hy
(defclass Something []
(defn --init-- [self] ....))
```
```hy
(defmacro blah []
`(defn --init-- [self] ...))
(defclass Something []
(blah))
```
Catching all of these may be problematic, so implementing this may not be entirely trivial. Mind you, if we catch the two most common cases (the first two), that would be useful too.
=> defclass should add an implicit nil return to --init--

docs/language/api.rst, hy/compiler.py, hy/lex/parser.py, tests/native_tests/language.hy
apply now mangles strings and keywords according to the Hy mangling
rules (by using the same function, now imported from
hy.lex.parser). With this change, if the dict passed to apply has
keywords, strings or quoted symbols, they'll get mangled, to turn them
into proper keys.
This only works for the cases where the keys are directly in the apply
params. A previously deffed dict, or key through a variable will not be
mangled.
This closes #219.
=> Teach apply about symbol mangling

docs/language/api.rst, docs/language/core.rst, docs/language/internals.rst, docs/style-guide.rst, docs/tutorial.rst, eg/twisted/get-page.hy, hy/contrib/alias.hy, hy/contrib/anaphoric.hy, hy/contrib/botsbuildbots.hy, hy/contrib/curry.hy, hy/contrib/loop.hy, hy/contrib/meth.hy, hy/core/bootstrap.hy, hy/core/language.hy, hy/core/macros.hy, hy/core/shadow.hy, scripts/reformat-changelog, scripts/update-coreteam.hy, tests/compilers/test_ast.py, tests/native_tests/contrib/anaphoric.hy, tests/native_tests/contrib/meth.hy, tests/native_tests/contrib/walk.hy, tests/native_tests/core.hy, tests/native_tests/defclass.hy, tests/native_tests/language.hy, tests/native_tests/mathematics.hy, tests/native_tests/native_macros.hy, tests/native_tests/py3_only_tests.hy, tests/native_tests/shadow.hy, tests/native_tests/with_test.hy
This drops the outer brackets from `let` and `with`, but does **NOT** change let behaviour anymore. That'll be another change, if at all.
See #713 and #852.
(Thanks for the reviews so far, the scope of this change was drastically reduced.)
=> A big let and with change

hy/core/language.hy
This allows us to react to things like "(foo))" being passed in instead of
looping until kingdom come. Also makes tokenizing things that are not
expressions easier:
=> (read)
"foo"
u'foo'
=>
=> Make `read` read line-wise and don't ignore lexer errors

hy/compiler.py, tests/compilers/test_ast.py, tests/native_tests/language.hy
Comparison operators such as `=`, `!=`, `<`, `>`, `<=`, `>=` should support a one-arity version too, and return true in those cases (except for `!=`, which returns false).
This closes #949.
=> Support one-arity comparison operators too

docs/tutorial.rst
Adds a short (require) example, along with a few words on why macros can't be imported.
Closes #966.
Signed-off-by: Csilla Nagyne Martinak <csilla@csillger.hu>
=> docs/tutorial: Add a short (require) example

hy/core/macros.hy
Borrowed from the API docs and Clojure, mostly.
Signed-off-by: Csilla Nagyne Martinak <csilla@csillger.hu>
=> hy.core.macros: Add docstrings for -> and ->>

docs/tutorial.rst
As part of the Grand Language Cleanup, a few examples in the tutorial could be simplified:
* The --init-- function of the defclass example does not need an explicit None anymore.
* The apply example in the Hy<->Python interop section can use a keyword instead of a string in the last part.
This perhaps closes #971.
Signed-off-by: Csilla Nagyne Martinak <csilla@csillger.hu>
=> docs/tutorial: Simplify two examples

docs/language/api.rst, hy/compiler.py, hy/core/bootstrap.hy, hy/core/macros.hy, tests/compilers/test_ast.py, tests/native_tests/language.hy, tests/native_tests/native_macros.hy
The `if` form now supports elif clauses.
It works like `cond` but without the implicit `do`.
closes #830.
The old `if` is still available as `if*`, but you don't need it since the 2- and 3- argument cases work exactly as before.
=> variadic if

hy/cmdline.py
This avoids dumping the whole traceback.
=> Nice-ify errors with hy2py and hyc

docs/tutorial.rst
I was reading the tutorial and found typos.
I didn't think it needed a feature/fix branch (might be wrong).
=> Typos in the tutorial

hy/compiler.py
=> Fix Python 3.5.1 support by converting kwargs and stararg to str as late as possible (thus preserving positional information)

.coveragerc
Cherry picked from commit b1f497ae7224911cc4712a4b8939cd75845a2942; PR #943
This should fix CI for the 0.11 hotfix branch.
=> Backport fix CI by moving exclude_lines

hy/compiler.py, hy/core/language.hy, hy/macros.py, tests/macros/test_macro_processor.py, tests/macros/test_reader_macros.py
This allows macros to take a keyword dict containing useful things by
defining a keyword argument. This allows us to pass in new objects
which might be handy to have in macros.
This changeset refactors module_name to become `compiler`, so that we
can pass the compiler itself into the macros as `opts['compiler']`.
This allows the macro to both get the macro name
(`compiler.module_name`), as well as use the compiler to build AST.
In the future, this will enable us to create "super-macros" which return
AST, not HyAST, in order to manually create insane things from userland.
For userland macros (not `defmacro`) the core.language `macroexpand`
will go ahead and make a new compiler for you.
=> Overhaul macros to allow macros to ref the Compiler

.travis.yml, Makefile, hy/compiler.py, setup.py, tests/native_tests/language.hy, tox.ini
(cherry picked from commit 9d8e4ddb8098dab39eb3d4f7ef89dc7ccd13a49f; PR #997)
=> Backport fix Python 3.5.1 support by converting kwargs and stararg to str as late as possible

hy/compiler.py, tests/compilers/test_compiler.py
This fixes #1010 for Python 3.3+. Unit tests check that the behaviour is unchanged in earlier versions, and I've checked they pass on 2.7,3.4 and PyPy.
=> In python 3.3+, generator functions always return a value

docs/language/api.rst
This adds documentation for the `&key` modifier as discussed in #961
=> Documentation of the &key modifier in (defn)

hy/contrib/anaphoric.hy, tests/native_tests/contrib/anaphoric.hy
I have rebased pull request #816 onto master and added a test case (as requested).
_Edit:_ Force-pushed an amendment that replaces `(except [e Exception] (assert (instance? HyMacroExpansionError e)))` with `(except [HyMacroExpansionError] true)` (as suggested by @kirbyfan64).
=> Fix anaphoric macro `ap-if`.

README.md
Add a link to XKCD to give proper attribution. Before this change, the attribution to XKCD 224 was only present in the alt text of the image, which is almost invisible in most browsers.
=> Give proper attribution

hy/compiler.py, tests/compilers/test_ast.py
See discussion in #961. Currently you can specify any type you like as the parameter "name" for a function when you use `&key` or `&optional`. This patch restricts it to be a `HyString`.
=> Keyword arguments to functions are required to be strings

hy/compiler.py
<s>Only test that seems to be failing is `Botsbuildbots`, and I think I know why... (Probably PyPy's ordered dictionaries.)</s> Actually, that was a problem with my setup. Only thing that failed was flake8.
=> Remove PyPy line number hack (closes #977)

hy/compiler.py, tests/native_tests/reader_macros.hy
This makes it possible to use strings as the macro name argument to `defreader`, which in turn makes it possible to define reader macros with names that would otherwise result in parse errors.
Such as `#.`.
This fixes #918.
=> defreader: Allow strings as macro names

README.md
When I see an XKCD comic, or an adaptation thereof, my first instinct is to look for title text. Not finding any, this proposes adding the original title text back in; if a good Hy-specific adaptation is proposed that'd be even better.
And no, this isn't important :)
=> Include original XKCD title text in comic image

docs/style-guide.rst
removed an incorrect extra bracket in the style guide.
=> minor doc fix

docs/tutorial.rst
_a_ or _some_ would work here, I opted to keep _a_
=> Remove redundant word in tutorial

docs/tutorial.rst, hy/compiler.py, tests/native_tests/native_macros.hy
=> Give an error when &kwonly is used in a macro definition

docs/contrib/index.rst, docs/contrib/walk.rst
Created documentation and code snippets for the `walk` contrib module, addressing #1053. Alphabetically sorted the TOC in `index.rst`.
=> Added documentation for walk, postwalk and prewalk

docs/contrib/loop.rst
In RestrutruedText, double backtick quotes (instead of single
backtick quotes in markdown) are used for code span.
---
docs/contrib/loop.rst | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
=> docs: contrib/loop: fix rst markup.

hy/compiler.py, hy/core/shadow.hy, tests/native_tests/mathematics.hy, tests/native_tests/shadow.hy
Fixes #1109.
`__pos__` doesn't work on strings, lists, or tuples, so I've removed some tests that required `(= (+ "a") "a")` etc.
I wanted to name the test `test-pos` instead of `test-add-unary`, but if I do that, the test doesn't get run, and I have no idea why.
=> Make unary + call __pos__

hy/compiler.py
In issue #1111, @tianon reported that Hy didn't work with Python
3.6.0b1: trying to evaluate a simple expression at the REPL blew up with
`TypeError: required field "is_async" missing from comprehension`. This
was due to a grammar
change (https://www.python.org/dev/peps/pep-0530/#grammar-updates) in
the implementation (https://hg.python.org/cpython/rev/cf91a929b81a) of
PEP 530, which we can easily accomodate.
=> fix Hy on recent Pythons

hy/models/set.py, tests/lex/test_lex.py, tests/models/test_set.py, tests/native_tests/language.hy, tests/native_tests/native_macros.hy
Fixes #1120.
I also added `hy.models._wrapper[set]` so a macro can return an ordinary set in place of a `HySet`.
=> Don't sort or deduplicate the items in a HySet

hy/cmdline.py
`--version` is [a GNU standard](https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html#g_t_002d_002dversion) that is also common for non-GNU programs, such as Python.
=> Allow --version as a synonym for -v

Makefile
Commit message:
I've marked added the rest of the phony build targets; wrapped the
recursive make call[0], and added the path specifier to the find
command for compatibility with BSD find.
[0]: https://www.gnu.org/software/make/manual/html_node/Recursion.html
Output of `make test`:
```
Name                      Stmts   Miss  Cover
---------------------------------------------
hy.py                        13      0   100%
hy/_compat.py                29      3    90%
hy/cmdline.py               213    162    24%
hy/compiler.py             1324     85    94%
hy/completer.py              95     75    21%
hy/contrib.py                 0      0   100%
hy/contrib/dispatch.py       20      1    95%
hy/core.py                    1      0   100%
hy/errors.py                 52     20    62% …
```
=>     Add PHONY targets; wrap call to recursive make; add path to find.

hy/core/language.hy, tests/native_tests/core.hy
This allows them to be used with numeric types that aren't built in, such as NumPy arrays. Because Python uses duck typing, there's generally no way to know in advance whether a given value will accept a given operator. Of course, things like `(inc "hello")` will still raise a `TypeError`, because so does `(+ "hello" 1)`.
=> Don't check the type of arguments to `inc`, `odd?`, etc.

hy/compiler.py, tests/compilers/test_ast.py
I consider this a bug-fix, since `lambda a=None, *xs: 1` is valid Python, but in Hy, you'd have to write that as `(fn [&rest xs &optional a] 1)` without this patch.
=> Allow &rest after &optional, like Python

hy/importer.py
Provide an import_file_to_globals function that can be used by the inferior lisp mode to load a file into the REPL namespace.
See:
https://github.com/vt100/hy-mode/tree/import_file_to_globals
=> Add import_file_to_globals for use in emacs inferior lisp mode

docs/contrib/anaphoric.rst, docs/contrib/flow.rst, docs/contrib/loop.rst, docs/contrib/multi.rst, docs/language/api.rst, docs/tutorial.rst, hy/cmdline.py, hy/compiler.py, hy/contrib/curry.hy, hy/contrib/loop.hy, hy/contrib/meth.hy, hy/macros.py, tests/compilers/test_ast.py, tests/native_tests/contrib/alias.hy, tests/native_tests/contrib/anaphoric.hy, tests/native_tests/contrib/botsbuildbots.hy, tests/native_tests/contrib/curry.hy, tests/native_tests/contrib/loop.hy, tests/native_tests/contrib/meth.hy, tests/native_tests/contrib/multi.hy, tests/native_tests/language.hy, tests/resources/tlib.py
You can now do `(require foo)`, `(require [foo [a b c]])`, `(require [foo [*]])`, and `(require [foo :as bar])`. The first and last forms get you macros named `foo.a`, `foo.b`, etc. or `bar.a`, `bar.b`, etc., respectively. The second form only gets the macros in the list.
Implements #1118 and perhaps partly addresses #277.
N.B. The new meaning of `(require foo)` will cause all existing code that uses macros to break. Simply replace these forms with `(require [foo [*]])` to get your code working again.
There's a bit of a hack involved in the forms `(require foo)` and `(require [foo :as bar])`. When you call `(foo.a ...)` or `(bar.a ...)`, Hy doesn't actually look inside modules. Instead, these `(require ...)` forms give the macros names that have periods in them, which happens to work fine …
=> Give `require` the same features as `import`

docs/language/api.rst, hy/core/macros.hy, tests/native_tests/language.hy
Adds docs and tets for as-> macro. I had trouble running tests locally, but now that I tried to reproduce it to write down the error message they passed. So please check if that happens on your machine too.
relates to #1047
=> Add docs and tests for as-> macro

docs/language/api.rst, docs/language/core.rst, docs/language/internals.rst, docs/style-guide.rst, docs/tutorial.rst, hy/compiler.py, hy/contrib/walk.hy, hy/core/language.hy, hy/core/macros.hy, hy/lex/parser.py, tests/compilers/test_ast.py, tests/native_tests/cons.hy, tests/native_tests/contrib/anaphoric.hy, tests/native_tests/contrib/loop.hy, tests/native_tests/contrib/walk.hy, tests/native_tests/core.hy, tests/native_tests/defclass.hy, tests/native_tests/language.hy, tests/native_tests/native_macros.hy, tests/native_tests/py3_only_tests.hy, tests/native_tests/quote.hy, tests/native_tests/unless.hy, tests/native_tests/when.hy
Per the straw poll in #908, as an alternative to #1147.
Now you must use `True`, `False`, and `None`, as in Python. Or just assign `true` to `True`, etc.; the old synonyms aren't reserved words anymore.
I got rid of `nil?`, too, since we also have `none?`.
=> Burninate the synonyms `true`, `false`, and `nil`

Makefile, tox.ini
Fixes #1157.
The new check is E305. Since we're now using the `--ignore` option, we have to list all the checks that are ignored by default, too.
I decided that ignoring E305 was better than changing the whitespace it was complaining about because, in at least some cases in our current codebase, single blank lines are used to indicate that several top-level definitions are associated with each other.
=> Ignore a new Flake8 whitespace error

AUTHORS, docs/language/core.rst, hy/core/__init__.py, hy/core/reserved.hy, hy/lex/parser.py, tests/lex/test_lex.py, tests/native_tests/core.hy
This is helpful for writing syntax highlighters (e.g., #1170).
=> Add a module for getting reserved words

tests/native_tests/language.hy
I have some macros for using pandas and NumPy that expect `:` to be a keyword instead of an ordinary symbol. These tests will ensure that we don't break this unless we want to.
=> Add tests for the empty keyword

docs/language/core.rst, hy/core/language.hy, tests/native_tests/core.hy
=> Add comp, constantly and complement

MANIFEST.in
Add a `MANIFEST.in` file to ensure that some other files get included in packages (e.g. `sdist`s on PyPI). In particular, include the author listing, the license file (as required by the MIT), the news/changelog, and the readme.
=> Add the manifest

hy/cmdline.py, tests/compilers/test_compiler.py, tests/lex/test_lex.py
Fixes:
```
hy/cmdline.py:175: DeprecationWarning: invalid escape sequence \_
tests/lex/test_lex.py:267: DeprecationWarning: invalid escape sequence \s
tests/compilers/test_compiler.py:45: DeprecationWarning: invalid escape sequence \*
```
when run against Python 3.6 with warnings enabled.
Found using [pydiatra](https://github.com/jwilk/pydiatra).
=> Fix invalid escape sequences

hy/compiler.py, tests/native_tests/language.hy
Unlike Python, Hy allows the programmer to intermingle positional and keyword arguments. This change removes an exception to that rule for method calls, in which the method callee always had to be the first thing after the method. Thus, `(.split :sep "o" "foo")` now compiles to `"foo".split(sep="o")` instead of `HyKeyword("sep").split("o", "foo")`.
=> Allow keyword args in method calls before the obj

NEWS, hy/core/shadow.hy, tests/native_tests/shadow.hy
Makes shadow operator behavior match normal (Python) operator behavior
when said operators are used in chained comparisons.
Unlike Python's `and`, the usage of `and` here is not short-circuiting.
Resolves #1191
=> Use `and` in hy.core.shadow.comp_op

CONTRIBUTING.rst, docs/language/api.rst, docs/style-guide.rst
Found using [urlycue](https://github.com/jwilk/urlycue).
=> Use HTTPS for github.com, docs.python.org and notes.pault.ag URLs

AUTHORS, docs/language/api.rst, docs/language/index.rst, docs/language/interop.rst, docs/tutorial.rst
I separated the existing text in two sections, with some additional explanations and a link to Hy's `import`.
=> Docs: Hy <-> Python interop fix #1061

NEWS, docs/language/api.rst, docs/language/core.rst, docs/language/internals.rst, docs/style-guide.rst, docs/tutorial.rst, hy/contrib/botsbuildbots.hy, hy/contrib/loop.hy, hy/core/bootstrap.hy, hy/core/language.hy, hy/core/macros.hy, hy/core/shadow.hy, hy/extra/anaphoric.hy, tests/compilers/test_ast.py, tests/native_tests/contrib/walk.hy, tests/native_tests/core.hy, tests/native_tests/defclass.hy, tests/native_tests/extra/anaphoric.hy, tests/native_tests/language.hy, tests/native_tests/mathematics.hy, tests/native_tests/native_macros.hy, tests/native_tests/py3_only_tests.hy, tests/native_tests/shadow.hy
See the discussion in #1056.
I haven't touched `scripts/reformat-changelog`, which still has some uses of `let`, because I'm not totally sure what it's supposed to do, so I wouldn't know how to check that I didn't break it.
- Closes #180 (I think)
- Closes #576
- Closes #619
- Closes #663
- Closes #664
- Closes #703
- Closes #1000
- Closes #1055
- Closes #1056
- Closes #1212
And maybe some other `let`-related bugs I didn't catch.
=> Burninate `let`

NEWS, docs/language/api.rst, hy/models/complex.py, hy/models/float.py, hy/models/integer.py, tests/lex/test_lex.py
You can use them as thousands separators.
This change differs from [PEP 515](https://www.python.org/dev/peps/pep-0515/) in that not only does it allow commas in addition to underscores, but it's much more liberal about placement. Any number of underscores or commas can be placed anywhere, even at the start.
=> Allow commas and underscores in numeric literals

hy/compiler.py, tests/compilers/test_ast.py
This prevents pointless imports of hy.core, like importing `map` in Python 3.
=> Don't put redundant names in _stdlib

NEWS, docs/extra/anaphoric.rst, docs/language/api.rst, hy/cmdline.py, hy/compiler.py, hy/core/shadow.hy, hy/extra/anaphoric.hy, tests/compilers/test_ast.py, tests/compilers/test_compiler.py, tests/importer/test_importer.py, tests/native_tests/language.hy, tests/native_tests/with_decorator.hy
=> Make `fn` work like `lambda` and remove `lambda`

hy/__init__.py, tests/compilers/native/quoting.hy
No NEWS entry is required because bytestrings are already a new feature.
=> Fix bug: quoting a bytestring raises ImportError

docs/language/api.rst, docs/language/core.rst, hy/contrib/multi.hy, hy/core/macros.hy, hy/extra/anaphoric.hy, tests/native_tests/cons.hy, tests/native_tests/language.hy, tests/native_tests/quote.hy
=> Remove `car` and `cdr` in favor of `first` and `rest`

AUTHORS, docs/tutorial.rst
I was following along and noticed that it wasn't actually explained how to _use_ the object we just made. I include both the `setv` style of writing the Hy as we've been using in the rest of the docs up to this point and a more LISP-y style use of the object.
=> Added class use example to tutorial

AUTHORS, docs/language/api.rst
Error message was
`NameError: name 'n' is not defined`
=> fix example in documentation to unquote in quasi quote

NEWS, docs/contrib/hy_repr.rst, docs/contrib/index.rst, docs/tutorial.rst, hy/cmdline.py, hy/contrib/hy_repr.hy, hy/importer.py, tests/__init__.py, tests/native_tests/contrib/hy_repr.hy, tests/test_bin.py
This pull request adds a function `hy-repr` and uses it to print out stuff in the REPL (edit: only when you launch Hy with `--hy-repr`).
Closes #351.
#1244 is a prerequesite. Merge that first and I'll rebase this.
An annoying consequence of this change (edit: now fixed, using the method listed second below) is that `setv` at the REPL now prints the value of whatever you assigned. I think this is bad because when I'm doing data analysis on the REPL, I often say things like `(setv x (some-function-that-produces-a-huge-pandas-dataframe))`, and I don't want that printed. I see two ways around this:
- Make `setv` always return `None`. The question of what `setv` should return, particularly in the REPL, is kind of a mess, anyway (#249, #871, #1049), so this change would eliminate another weird …
=> Homoiconic REPL

NEWS, hy/contrib/loop.hy, tests/native_tests/contrib/loop.hy
Since this change removes the undocumented function `hy.contrib.loop.recursive-replace` (I've used `hy.contrib.walk.prewalk` instead), it closes #465.
=> Fix bug: `loop` replaced strings equal to "recur"

docs/language/core.rst
[Current master branch NEWS file says](https://github.com/hylang/hy/blob/a27d737e1c6273dcb4c377d123392fc1951b3150/NEWS#L413):
> * Removes setf in favour of setv
=> Switch from setf to setv according to NEWS

AUTHORS, NEWS, docs/language/api.rst, hy/core/macros.hy, tests/native_tests/language.hy
Modified cond to support single argument branches as requested in #1084.  This is my first contribution, so I'd appreciate feedback.
Closes #1084.
=> cond accept single-argument branches

docs/tutorial.rst
It was missing quotes around "Tuukka". Output from hy to confirm everything's good:
```clojure
hy unknown using CPython(default) 3.6.1 on Linux
=> (print "Hello there," "Tuukka")
Hello there, Tuukka
```
=> Fix Tuukka print example

docs/coreteam.rst
It's been fun, but with other projects taking up my attention, I haven't been paying attention to Hy for a number of months, and it seems more responsible for the core team list to reflect this.
=> retHyrement

NEWS, docs/language/api.rst, docs/tutorial.rst, hy/compiler.py, hy/completer.py, hy/core/macros.hy, hy/lex/lexer.py, hy/lex/parser.py, hy/macros.py, tests/macros/test_tag_macros.py, tests/native_tests/tag_macros.hy, tests/test_lex.py
Closes #1046 
(See also #1230.)
This also changes the "sharp macro" term to "tag macro", to better match with Clojure. (And besides, the ASCII Number Sign `#` isn't the same as the Unicode `♯` Music Sharp Sign. This was misleading--They're similar but note that the horizontal lines of `#` wouldn't show up well on the musical staff.)
=> Tag macros

Makefile, NEWS, hy/lex/parser.py, tests/native_tests/language.hy, tests/test_lex.py
=> Don't parse 5.attr or :foo.attr as symbols

tests/test_bin.py
Change run_cmd for test_bin.py to use universal newlines (text mode) for Windows compatibility.
Is there some reason this popen has to be done in binary mode? Windows does line endings differently, which makes a test fail on Windows. #1289. The other failing test shown in that issue isn't fixed by this though.
=> universal newlines in test

NEWS, docs/language/api.rst, docs/language/core.rst, hy/cmdline.py, hy/compiler.py, hy/core/language.hy, hy/importer.py, hy/macros.py, hy/models.py, tests/compilers/test_ast.py, tests/native_tests/language.hy, tests/native_tests/native_macros.hy
=> Auto-promote values to HyObjects in the compiler

NEWS, hy/compiler.py, hy/macros.py, tests/native_tests/language.hy
=> Require HySymbols instead of HyStrings in more cases

NEWS, hy/compiler.py, hy/core/macros.hy, tests/native_tests/native_macros.hy, tests/native_tests/py3_only_tests.hy
Backports of Python 3 features to Hy under Python 2 aren't worth the effort of supporting. It's Hy time for people to upgrade.
- Closes #691.
- Closes #692.
=> Remove the Python 2 yield-from macro

hy/core/macros.hy
Fixes #1016.
There are no tests and no NEWS updates because #1016 arguably isn't a bug per se (you're not supposed to import `hy.core.macros` outside Hy itself). Still, it's probably good practice to avoid using a core macro (other than the bootstrap macros, of course) in the definition of another.
=> Don't use `cond` in the definition of a core macro

AUTHORS, NEWS, docs/language/api.rst, hy/compiler.py, tests/native_tests/quote.hy
The original `unquote_splice` received a form stored in the variable `f_contents`, and produced the code
```clojure
`(list ~f_contents)
```
This PR modifies this to the following code, providing an additional `var = self.get_anon_var()`:
```clojure
`(do
(setv ~var ~f_contents)
(if* (= ~var None)
[]
(list ~var)))
```
I have ran and passed the `tox` tests a Fedora Linux with Python versions 2.7, 3.3.6, 3.4.6, 3.5.3, 3.6.2, pypy-5.7.1, installed through pyenv. I also ran
```clojure
(defmacro splicetest []
`[1 2 ~@[3 4] ~@None 5 6 ~@(when False 0) 7 8 ~@(when True None) 9 10 ~@(when True [None]) 11 12 ~None])
(splicetest)
```
through `hy2py`, and got
```python
import hy
from hy import HyInteger, HyList
def _hy_anon_fn_1():
_hy_anon_var_1 = [3, 4]
_hy_anon_var_2 = None
_hy_anon_var_3 = None …
```
=> Allow `unquote-splice` to accept any false value as empty

AUTHORS, NEWS, hy/contrib/multi.hy, tests/native_tests/contrib/multi.hy
A defn mult-arity method returning a value evaluating to None currently raises a TypeError:
```
(require [hy.contrib.multi [defn]])
(defn fun                                                                                              
([] ""))
(fun)  ;; raises TypeError
```
With this PR the value is returned instead.
=> Fix TypeError when defn multi-arity method returns None

AUTHORS, NEWS, docs/language/interop.rst, hy/__init__.py, hy/core/language.hy, tests/importer/test_importer.py
Fixes #1256 (and replaces #1365)
=> Expose `read`, `read_str`, and `eval` in Python

AUTHORS, hy/completer.py
Replaces malformatted PR #1356 
Without the check, the next line will reference readline even if the library was not successfully loaded.
=> hy/completer.py:27 docomplete truth check

hy/models.py, tests/test_models.py
I encountered this, while trying to fix PR #1374:
```
(import [hy.models [HyComplex]])
(import [copy [copy deepcopy]])
(setv x (HyComplex 42j))
(copy x)      ;; returns 0j
(deepcopy x)  ;; returns 0j
```
using a literal or the python builtin `complex` everything works as expected:
```
(setv y 42j)
(copy y)       ;; returns 42j
(deepcopy y)   ;; returns 42j
(setv z (complex 42j))
(copy z)       ;; returns 42j
(deepcopy z)   ;; returns 42j
```
The proposed solution is to explicitly implement `__copy__` and `__deepcopy__` in HyComplex.
=> Fix copy behaviour of HyComplex

NEWS, hy/compiler.py, tests/compilers/test_ast.py
This PR fixes Issue #1350 in a rather hacky way (at least I am fixing a method called `_compile_time_hack`). The problem seems to be, that the try form is compiled several times: once within `hy.importer.hy_eval` and the second time within `compiler.HyASTCompile._compile_time_hack`. The proposed solution simply passes a copy to the first method.
Not sure how to test this though...
=> Fixes #1350: try form in defmacro

hy/compiler.py, tests/native_tests/language.hy
=> Add `return` as a special form

NEWS, docs/language/api.rst, hy/core/macros.hy, hy/lex/lexer.py, hy/lex/parser.py, tests/native_tests/core.hy, tests/test_lex.py
Closes #1058.
This still needs docs, a `comment` macro, and lots of tests. [Edit: and a news mention!] But I'd like to verify my approach first.
The `#_` syntax needs to be at the "reader" level. It can't be a simple macro. The lexer is too low-level for this. A regex is enough for `;` comments, but the `#_` syntax needs to be able to identify Hy forms properly, even when they contain nested brackets. So I added an "empty" production to the grammar in the parser to make it work. 
I had to add the "empty" production in a lot of places to avoid shift/reduce warnings. This does complicate the parser a bit. If someone has a more elegant approach, I'd like to see it.
=> add #_ discard syntax

NEWS, hy/compiler.py, hy/core/language.hy, hy/core/macros.hy, tests/native_tests/language.hy
- Closes #841.
- Fixes #1068.
See the discussion in #1346.
=> Make `assoc` a macro instead of a special form

NEWS, tests/native_tests/language.hy
Closes #1207.
It looks like #1374 fixed this bug and nobody noticed. Nice going, @schaefed.
=> Un-xfail a passing test of `macroexpand`

.travis.yml, NEWS, hy/_compat.py, hy/compiler.py, hy/importer.py, setup.py, tests/native_tests/language.hy, tox.ini
[3.3 will no longer be supported by the Python people on September 29th](https://docs.python.org/devguide/#status-of-python-branches), and our next release will be after that.
=> Drop support for Python 3.3

conftest.py, hy/importer.py, tests/test_bin.py
Also improve `test_bin_hy_builtins` and warn that it fails from IPython.
The shell on Windows needs double quotes. This is a partial fix for #1289. It's *still* not runnning the native tests, but I wanted to push this much to make sure switching the quotes doesn't break it for Travis.
[Edit: got the native tests working on Windows too. Fixes #1289.]
=> fix testing for windows

NEWS, docs/language/api.rst, docs/language/internals.rst, hy/compiler.py, hy/lex/lexer.py, hy/lex/parser.py, hy/models.py, tests/compilers/test_ast.py, tests/native_tests/language.hy, tests/test_lex.py
- Closes #1042.
- Closes #1287.
- Replaces #1327.
To do:
=> Add #[DELIM[ … ]DELIM] syntax for string literals

hy/compiler.py, tests/compilers/test_compiler.py, tests/native_tests/language.hy
More could be done, but this is progress. It saves a few hundred lines from the compiler by removing various kinds of duplication. There should be no changes to Hy semantics, although the exact generated AST is different in some cases.
=> Compiler refactor

NEWS, docs/language/api.rst, hy/models.py, tests/native_tests/language.hy, tests/test_lex.py
Fixes https://github.com/hylang/hy/issues/1340.
=> Treat _42 etc. as a variable name, not an integer

docs/contrib/walk.rst, docs/language/api.rst, docs/language/core.rst, docs/language/internals.rst, hy/contrib/hy_repr.hy, hy/models.py, tests/test_models.py
Closes #914.
This will make development of macros sooo much easier, since we can tell exactly what we're looking at in the repl with macroexpand or any other manipulations of Hy models.
The reprs for HyList and derivatives will use two-space indents, so even deeply nested structures are readable in the repl.
This also makes the reprs valid Python code to reconstruct the hytree in most cases, as is preferred in Python. This will improve Python interop somewhat, since if a Hy model leaks through, the error message will make sense as a Hy model, instead of looking like Hy code that could be confused for some kind of Python display.
=> proper reprs for Hy models

AUTHORS, hy/core/bootstrap.hy, hy/core/language.hy, hy/core/macros.hy, hy/core/shadow.hy
Now that we are getting some good documentation introspection utilities in `hy-mode`, Hy's exposed docstrings should be standardized.
Only docstrings were modified in this commit.
I changed formatting and wording in `hy.core.language`, `hy.core.shadow`, and `hy.core.macros` to:
1. First line is always one sentence with period.
2. Use the argument names in the first line and backtick them.
3. Further lines do not include spaces.
=> Standardize hy.core docstrings

NEWS, hy/errors.py, tests/test_bin.py
=> Fix a crash in HyTypeError.__str__

NEWS, docs/extra/anaphoric.rst, hy/extra/anaphoric.hy, tests/native_tests/extra/anaphoric.hy
As discussed in #1439. This replaces `xi` with a more Clojure-like `#%` tag macro.
=> change xi macro to #% tag macro

NEWS, docs/language/api.rst, hy/core/macros.hy, hy/macros.py
Closes #356.
This isn't exactly what was asked for, but we have three separate namespaces to deal with here--macros, tag macros, and runtime objects. It's entirely possible to have the same name in all three namespaces. Rather than trying to get `help` to work with all three somehow, this adds a `doc` macro for help with macros, and a `#doc` tag macro for help with tag macros. Using a macro to look up macros and a tag macro to look up tag macros seems easy to remember.
The other option would be to shadow the builtin `help` with a `help` macro. When passed a quoted symbol, it would look up the macro. When passed a keyword it would look up the tag macro with that name. When passed any other object, it would defer to Python's `help`. It seems a lot less intuitive though.
=> add documentation macros

hy/cmdline.py, hy/compiler.py, hy/core/language.hy, setup.py, tests/native_tests/language.hy, tests/native_tests/native_macros.hy, tests/test_bin.py
Fixes #1446.
The new astor is much improved. You can actually read quasiquoted forms in Python now.
I've almost got this working, but Hy's `NaN` literal crashes astor and I'm not sure what to do about it.
Astor also prints off `Inf` as `1e1000` instead now.
One option is to remove the three literals, `Inf`, `-Inf`, and `NaN` from Hy. Python doesn't have them, but since 3.5 has a `math.nan` and `math.inf`. It would save on the extra code from #1294.
We're kind of exploiting an implementation detail of the ast to make these literals, so it's not that surprising that astor can't handle them. (We could kind of say the same of Hy's expanded character set for symbols, but that's used by more than Hy--e.g. by pytest's rewriting of `assert`s.) Our astor-based `hy2py` tool doesn't always produce …
=> update astor to 0.6

AUTHORS, docs/language/interop.rst
(A typo made use of Print function, which is not defined)
=> Update interop doc: print function is lower-case

docs/conf.py
Fixes:
conf.py:12: DeprecationWarning: invalid escape sequence \Z
when building docs using Python 3.6 with warnings enabled.
=> docs/conf.py: make regexp string raw

hy/models.py, tests/test_lex.py
Fixes #1448.
There's no NEWS entry because this was a regression since the previous release.
=> Don't parse large floats as symbols

NEWS, docs/contrib/walk.rst, docs/extra/anaphoric.rst, docs/language/api.rst, docs/language/core.rst, docs/style-guide.rst, hy/compiler.py, hy/contrib/multi.hy, hy/contrib/sequences.hy, hy/core/language.hy, tests/native_tests/contrib/walk.hy, tests/native_tests/core.hy, tests/native_tests/language.hy, tests/native_tests/mathematics.hy, tests/native_tests/tag_macros.hy
Simply removed `def` keyword and replaces it with `setv` everywhere. See #1475 and #911.
=> Just remove `def`

conftest.py
Just a small cleanup - this works now since python 3.1.0, and already pin travis to use >= 3.2.1
=> Simplify conftest for loading hy modules

CONTRIBUTING.rst
@hylang/core
It's not a secret that in the year and a half I've been working on Hy, I've been frustrated by how slowly PRs get reviewed and merged. I think the current policy of requiring two core-team reviewers other than the author would be fine if the core team were more active. But the core team isn't very active. It's nobody's fault; it's just that we're often busy with our jobs and other responsibilities.
I'm proposing a policy change that allows for an alternative way for a PR to be cleared to merge: if it's at least **two weeks** old and **no** member of the Hy core team has expressed disapproval of the PR in its current state. This means that the author can merge the PR without help if he's a core member, or with only one core member's help if he isn't. At the same time, any core …
=> Policy: allow PRs to be merged more easily

Makefile, NEWS.rst, hy/compiler.py, hy/contrib/sequences.hy, hy/core/language.hy, hy/importer.py, hy/inspect.py, hy/macros.py, setup.cfg, tests/compilers/test_ast.py, tests/test_bin.py, tests/test_lex.py, tox.ini
Deal with almost everything except the deprecation of `inspect.getargspec`. I have code that deals with that as well, but I haven't made it fully py2/py3 compatible just yet. Since that's a larger change, I figured I'll put it up separately and put in smaller changes first.
There is one necessary AST generation change that needs to land to let us properly handle PEP 479, and something that I think that should be considered a bug to begin with: `(return)` transforms into `return None` when it should transform to just `return`.
This is because a naked `return` is valid in Python 2 as a way to exit a generator. `return` with a value isn't supported till Python 3.2 or 3.3, can't remember.
While its a deprecation warning now, its default behaviour come python 3.7 (which is in beta) so probably …
=> Deal with some deprecation and resource warnings / fix (return) semantics

README.md
PyPI shields are "no longer available", and we haven't updated Coveralls since Jaunary 2016.
=> Remove obsolete shields in README

NEWS.rst, hy/compiler.py, tests/native_tests/language.hy, tests/native_tests/operators.hy, tests/native_tests/tag_macros.hy
There were a bunch of tests where we had typos like `(= (f a b))` instead of `(= (f a) b)`.
=> Make unary comparison ops evaluate their argument

tests/compilers/test_ast.py
Some cleanups I noticed when going through #1529, but figured I'd do it separately in case that PR is rejected.
`pytest.raises` captures the exception so you can inspect the error message.
=> Use pytest.raises for asserting compiler exceptions

.travis.yml, NEWS.rst, hy/compiler.py, hy/core/language.hy, hy/importer.py, setup.py, tests/compilers/test_ast.py, tests/native_tests/contrib/hy_repr.hy, tests/native_tests/language.hy, tests/resources/module_docstring_example.hy
These changes should suffice to make us Python 3.7-ready (#1501), except that berkerpeksag/astor#86 is still a blocker.
Update: the astor bug is fixed, so this closes #1501.
=> Python 3.7 support

hy/models.py
Improves error reporting just a tiny bit by including offending objects and thus making debugging easier
=> Report objects when raising type error

hy/_compat.py, hy/lex/parser.py
When `hy` python compiled with UCS-2, the unit tests failed because in the [mangle function](https://github.com/hylang/hy/blob/master/hy/lex/parser.py#L54), `😂` unicode represents as two 16bit int `0xD83D` `0xDE02` rather than one 32bit int `0x1F602`.
This problem only affects before Python version 3.3 ([PEP 393](https://www.python.org/dev/peps/pep-0393/) uses UCS-4 on all systems).
ref:
[1] https://docs.python.org/2/howto/unicode.html#the-unicode-type
[2] https://docs.python.org/3/library/sys.html#sys.maxunicode
=> Fix `mangle` for Pythons compiled with UCS-2

hy/cmdline.py
Previously the `hy -h` helping message looks like this:
```
usage: hy [-h | -i cmd | -c cmd | -m module | file | -] [arg] ...
optional arguments:
-h, --help            show this help message and exit
-c COMMAND            program passed in as a string
-m MOD                module to run, passed in as a string
-i ICOMMAND           program passed in as a string, then stay in REPL
--spy                 print equivalent Python code before executing
--repl-output-fn REPL_OUTPUT_FN
function for printing REPL output (e.g., hy.contrib
.hy-repr.hy-repr)
-v, --version         show program's version number and exit
--show-tracebacks     show complete tracebacks for Hy exceptions
file         program read from script
module       module to execute as main
-            program read from stdin
[arg] …
```
=> Prettify hy command helping message

NEWS.rst, hy/compiler.py, tests/compilers/test_ast.py, tests/native_tests/defclass.hy
Okay, so back to square one, and this one I think is a much better fix. Address a few issues all at once.
- Fixes #1533. The problem there was in the \_\_init__ return suppression.
- Tweaks class construction so we emit a list of statements.
- Remove `__doc__` attribute setting. Python looks at the first ast.Expr statement in its body, we don't need to really handle it specially.
Now the only problem I have, and could use some help, is with `force_stmt`. I duplicated the function because `expr_as_stmt` drops statments. For example, consider I get back:
Result(imports=[], stmts=[FunctionDef(name='foo', args=arguments(args=[], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=[Pass()], decorator_list=[])], expr=None, contains_yield=False)
Its already a statement but …
=> Fix `defclass`

NEWS.rst, hy/cmdline.py, tests/resources/bin/printenv.hy, tests/test_bin.py
This commit adds `-E` support for Hy. Similar to Python, hy will ignore
all PYTHON* environment variables, e.g. PYTHONPATH and PYTHONHOME,
that might be set.
This is an enhancement mentioned in https://github.com/hylang/hy/issues/1488
=> Add -E support for Hy REPL

.gitignore
The `.pytest_cache/` folder appears after running `make test` locally.
This commit also updates vim temporary files exclusion rules.
=> Update .gitignore to exclude pytest cache folder

docs/language/syntax.rst, hy/lex/parser.py, tests/native_tests/mangling.hy
=>  Use `X` as the mangle delimiter on Python 3 

NEWS.rst, docs/language/core.rst, docs/language/syntax.rst, hy/compiler.py, hy/contrib/hy_repr.hy, hy/core/language.hy, hy/lex/parser.py, hy/models.py, tests/native_tests/contrib/hy_repr.hy, tests/native_tests/language.hy, tests/test_lex.py
HyKeywords are no longer string instances with a particular prefix, but a completely separate object.
It also means HyKeywords now evaluate to themselves as well.
I'm splitting up #1504 into two parts, especially since I basically need to rewrite the `HySymbol` work now that the mangling changes went in.
I want to break the current loose typing between `HyKeyword` / `HySymbol` / strings. I think it mostly  makes the compiler's core messier than it should be.
I think I've changed my mind and that it makes a lot of sense to continue to keep `HySymbol` a subclass of `str`, but I think we might be able to make some improvements that improve the type safety of the compiler's core without needing `isinstance(foo, HySymbol)` checks everywhere.
=> Make HyKeyword a first class objects

tests/importer/test_importer.py, tests/test_bin.py
When set, it will conflict with any tests that generate bytecode because they don't expect it to be set.
Fixable by sanitize the environment before forking, but we can't do anything about import tests.
This is a pipenv default, and possibly a sane flag to set while doing Hy development, so lets not let it be a hazard for developers to trip over.
=> Fix unit tests when run with PYTHONDONTWRITEBYTECODE

NEWS.rst, hy/compiler.py, hy/core/macros.hy, tests/compilers/test_ast.py, tests/native_tests/language.hy
=> Allow `while` and `for` with empty bodies

hy/contrib/botsbuildbots.hy
The change in #1582 is preventing Hy from installing.
Closes #1599
#1601 would make this moot, but fixing it is the more conservative change. Pick one or the other. This `botsbuildsbots` doesn't do anything important. It's just one of our Easter eggs.
=> fix botsbuildbots for #1582

hy/contrib/walk.hy, tests/native_tests/contrib/walk.hy
Fixes #1602. The first element after the `.` should be expanded normally, even if it's a symbol.
=> Fix bug in let's handle-dot.

NEWS.rst, docs/extra/anaphoric.rst, hy/extra/anaphoric.hy, tests/native_tests/extra/anaphoric.hy
Anaphoric macros do not work well with point-free style programming, in
which case both threading macros and `comp` are more adequate.
=> Fixes #1605: remove macros ap-pipe and ap-compose

hy/compiler.py, hy/core/shadow.hy
_stdlib is a global variable, so core modules could use it, contrary to our intention, so long as they happened to be compiled after a non-core module. I've added a compiler attribute to track whether we can use _stdlib.
This fix exposed some cases where hy.core.shadow tried to use a core function, so I fixed those.
I've also added an `if not _stdlib` to `load_stdlib` so that we only bother to actually load _stdlib once.
=> Fix the management of _stdlib

hy/lex/parser.py, setup.py
Closes #1598.
See the commit message for performance tests.
=> Disable the parser cache

.travis.yml, hy/compiler.py, tests/native_tests/language.hy
Closes #1627.
We need to both stop testing the old Python 3.7 on Travis, and fix our code to work on the latest Python 3.7.
=> Get  Travis and Python 3.7 working again

AUTHORS, NEWS.rst, hy/core/macros.hy, tests/native_tests/native_macros.hy
Being able to have o!-symbols in lists nested in the arglist of `defmacro!` seems like a good idea to me. Otherwise one couldn't do things like
(defmacro! if-let [[sym o!expr] then else]
`(if ~g!expr (let [~sym ~g!expr] ~then) ~else))
If this is not allowed, `defmacro!` is pretty useless for writing `if-let` in particular; at least I *think* so.
The tests didn't pass before I started. :P
=>  Look for o!-syms in (flatten args) of defmacro!

NEWS.rst, hy/compiler.py, tests/compilers/test_ast.py
=> Make importing a dotted name a syntax error, per Python

issue_template.md
I've closed half-a-dozen reports of bugs that were already fixed.
=> Add reminder to check master before reporting bugs

hy/contrib/walk.hy, tests/native_tests/contrib/walk.hy
fixes #1645 
Also adds a test for the issue, and cleans up the two files.--proper special indent for let tests, and removes some outdated comments in the walk module.
=> Fix let rebind bug.

issue_template.md
I occasionally see issues like #1667, #1666, #1595, etc. that probably shouldn't be on our issue list.
I considered adding a RTFM--sometimes these questions are about simple things that are clearly spelled out in the manual, but it can be hard to search it for special characters. (It might be easier to clone and grep the repo just to find the right docs sometimes.)
Does anyone still check the mailing list? I pretty much never use it. I am watching the `[hy]` tag on Stack Overflow, and would usually get around to checking our IRC channel via Matrix within about a day.
Also helps a little with #1357.
If anyone feels they can word this more politely without losing clarity for someone in a hurry, feel free to push changes.
I'd call this a doc fix, so one approval will suffice.
=> Point out appropriate help forums

AUTHORS, NEWS.rst, hy/contrib/walk.hy, tests/native_tests/contrib/walk.hy, tests/resources/macros.hy
Minor change that allows `macroexpand-all` to expand `require`d macros.
See [this discussion for some context](https://github.com/algernon/adderall/pull/9#issuecomment-407560245).
=> Expand `require`d macros in `macroexpand-all`

fastentrypoints.py, hy/cmdline.py, hy/compiler.py, hy/core/language.hy, hy/lex/__init__.py, hy/lex/parser.py, hy/macros.py, setup.py
On my machine, with Python 3.7, running a byte-compiled program `(print  "hi")` with master takes 0.190 s, compared to 0.073 s with these changes.
=> Some simple speed-ups

NEWS.rst, conftest.py, docs/contrib/walk.rst, hy/_compat.py, hy/cmdline.py, hy/compiler.py, hy/contrib/walk.hy, hy/core/macros.hy, hy/importer.py, hy/macros.py, tests/compilers/test_ast.py, tests/importer/test_importer.py, tests/importer/test_pyc.py, tests/native_tests/native_macros.hy, tests/resources/bin/__main__.hy, tests/resources/importer/circular.hy, tests/resources/importer/docstring.hy, tests/resources/importer/foo/__init__.hy, tests/resources/importer/foo/__init__.py, tests/resources/importer/foo/some_mod.hy, tests/resources/importer/foo/some_mod.py, tests/resources/relative_import.hy, tests/test_bin.py
These changes implement a new importer using `sys.path_hooks` and `importlib` semantics.  This is more-or-less a completely different approach from https://github.com/hylang/hy/pull/1671 and, its origin, https://github.com/hylang/hy/pull/1518.
Python 3.x is patched in a way that integrates `.hy` source files into Python's default `importlib` machinery.  In Python 2.7, a [PEP-302](https://www.python.org/dev/peps/pep-0302/) "importer" and "loader" is implemented according to the standard `import` logic (via `pkgutil` and later pure-Python `imp` package code).
In both cases, the entry-point for the loaders is through `sys.path_hooks` only.  As well, the import semantics have been updated all throughout to utilize `importlib` and follow aspects of …
=> New patch importer

NEWS.rst, hy/compiler.py, tests/compilers/test_ast.py, tests/resources/pydemo.hy, tests/test_hy2py.py
This closes hylang/hy#1367, closes hylang/hy#1540
=> Fix AST handling of docstrings and __future__ ordering

hy/cmdline.py, hy/importer.py, tests/resources/no_extension, tests/test_bin.py
Adds Hy parsing of files with unrecognized source extensions to cmdline Hy.
~~The fallback is tried only after first attempting standard Python compilation.  If the attempt raises a `SyntaxError` (and the file is not clearly identified as Python source via its extension), then it tries Hy.
The reason for choosing the order Python-then-Hy is somewhat arbitrary, except for the impression that Python's parsing might be more efficient than Hy's and, thus, better as a first attempt.~~
=> Allow `runpy` to consider non-standard Hy source extensions

hy/core/macros.hy, tests/native_tests/core.hy
The doc macro expands without importing `importlib.import_module`, so, if the expansion namespace doesn't have `import_module` present, `doc` will fail.  This PR corrects that and introduces a missing test for the `doc` macro.
=> Fix missing import in `doc` macro expansion

hy/importer.py, tests/importer/test_importer.py, tests/resources/fails.hy
Newly imported modules with compile and/or run-time errors were not being removed from `sys.modules`.  This commit modifies the Python 2.7 loader so that it follows Python's failed-initial-import logic and fixes the issue.
=> Fix `sys.modules` for failed imports in Python 2.7

NEWS.rst, docs/language/core.rst, hy/cmdline.py, hy/compiler.py
Every call to `hy_eval` and `hy_compile` will create a new `HyASTCompiler` instance, which incurs Hy standard library setup costs each time.  When calls to these functions occur more than once (e.g. by use of `HyREPL` and `eval-and-compile`), the aforementioned work is performed unnecessarily for the same module.  These changes avoid that unneeded and error-prone repetition.
=> Reuse Hy compiler instances

hy/macros.py, tests/native_tests/native_macros.hy
This change makes it possible to do things like require a library full of macros. It also increases consistency with Python's usual import system.
I haven't edited NEWS, since this change is a return to 0.15 semantics.
=> Make (require [foo [*]]) pull in macros required by `foo`

docs/language/api.rst
#1527 
The following works with bar.__doc__ returning "bar":
(defclass bar [] "bar" [attr "value"]) 
while the following does not:
(defclass bar [] [attr "value"] "bar")
(bar.\_\_doc__ evaluates to bar.\_\_doc__ itself.)
This seems to be the intended python-ic behaviour, if I am not wrong.
=> added documentation for defclass docstring

NEWS.rst, docs/language/syntax.rst, hy/compiler.py, hy/lex/__init__.py, hy/lex/lexer.py, hy/lex/parser.py, hy/models.py, tests/compilers/test_ast.py, tests/native_tests/language.hy, tests/test_lex.py
- Closes #1239.
- Closes #1740.
This implementation follows my proposal in #1740, except that I did end up allowing conversion specifiers and format specifiers in nested replacement fields, because they were easier to implement than not, and allowing them is consistent with Python, anyway.
I did~~n't~~ include compatibility for pre-3.6 Pythons because ~~I didn't feel like putting in the additional effort to get it right (e.g., `str.format` and `unicode.format` are unhelpful because they won't evaluate expressions in nested fields, and you can't call `repr` because it might be shadowed by another variable). One could still add this as a later PR.~~ it turned out to be easier than I'd expected.
The lexer fixes were necessary to write the function `parse_one_thing`.
=> Format strings

AUTHORS, NEWS.rst, hy/importer.py
The `dir` parameter removed by this commit caused hy to try to create a
temporary file where it is installed. This caused problems for the NixOS
package as it would be installed in the Nix store which is a read-only
filesystem.
I ran the tests and most of them passed. I rolled back my branch to master and ran them again and it appears the tests that failed were also failing on master. I've used hy with these changes and am fairly confident that they don't cause any issues.
Information on the issues facing the NixOS package can be found here: https://github.com/NixOS/nixpkgs/pull/57882
=> Allow Hy to run when installed in read only filesystem

setup.py
I wrote an RPM package for hy (which you can find [here](https://github.com/eklitzke/hy-rpm/)) and ran into a kind of weird thing during packaging. Right now `get_version` is specified in `data_files`, which means that it's installed into `/usr` or `/usr/local` by default when installing hy. However, this file isn't actually needed at all by hy: it's only used in the `setup.py` script and the `docs/conf.py` file, so it's really a build dependency and not an install dependency. In fact, the `setup.py` file creates `hy/version.py` which is installed the usual way, and contains the version which can be queried at runtime:
```
$ hy
hy 0.16.0+20.gb31863d using CPython(default) 3.7.2 on Linux
=> (import hy.version)
=> hy.version.--version--
'0.16.0+20.gb31863d'
```
This part of the `setup.py` …
=> get_version is not needed in data_files

NEWS.rst, hy/compiler.py, tests/native_tests/language.hy
Fixes #1790. This avoids compiling them more than once while also applying some simplification.
=> Rework statements in while condition

hy/__main__.py, hy/importer.py, setup.py, tests/importer/test_pyc.py, tests/test_hy2py.py
- We can just hardcode the `*3` scripts, no Python 2 left.
- Remove remaining uses of `imp`. The previous code incorrectly assumed the functions used (`spec_from_file_location` and `module_from_spec`) were unavailable prior to Python 3.6, whereas they were added in 3.4 and 3.5, respectively. (The former *was* modified to take path-like objects in 3.6, which is where the confusion may have come from).
=> Pre-Python 3.4 cleanup (including Python 2)

docs/contrib/profile.rst
The link http://www.graphviz.org/Home.php results in a 404.
=> Fixed broken link to Graphviz

NEWS.rst, docs/language/internals.rst, hy/compiler.py, hy/contrib/hy_repr.hy, hy/contrib/multi.hy, hy/contrib/walk.hy, hy/core/macros.hy, hy/models.py, tests/native_tests/contrib/walk.hy, tests/native_tests/quote.hy, tests/test_models.py
Closes #1542.
The key change here is a small one: changing `HySequence` to inherit from `tuple` instead of `list`. All the other changes are support or unrelated cleanup.
Hy models are still mutable in their attributes, which is convenient for `.replace`. I think that removing the ability to change which elements a `HySequence` contains is the main thing we need to avoid nasty surprises from model mutation.
=> Immutable Hy models

NEWS.rst, hy/completer.py
=> Avoid a crash when we can't access a history file

AUTHORS, get_version.py
Noticed this while packaging hy for Alpine Linux. On Alpine package
builders git is installed by default and all packages are build in
subdirectories of the package git repository. This causes git_version.py
to output the version of the package repository since it doesn't consult
the VERSIONFILE first.
This commit reverse the logic checking for the VERSIONFILE first and
only falling back to git-describe if the version file doesn't exist. I personally
think that it is more logical to do it that way.
=> get_version.py: Prefer VERSIONFILE over git-describe(1)

NEWS.rst, docs/language/api.rst, docs/tutorial.rst, hy/compiler.py, hy/core/bootstrap.hy, hy/core/macros.hy, hy/lex/lexer.py, hy/lex/parser.py, tests/native_tests/language.hy, tests/native_tests/py36_only_tests.hy
Ref. #1794. I'm going to split this up into more commits (partly since I ended up majorly reworking the function argument parsing code) but figured I should get the initial WIP out there for a basic overview. The syntax used is identical to the accepted proposal in #1794.
=> Implement PEP 3107 & 526 annotations

NEWS.rst, tests/compilers/test_compiler.py
If HyASTCompiler is given a string, it imports it and uses it as the execution environment. However, the unit tests gave HyASTCompiler the string 'test', assuming it would create a new test module, when in
reality it would import CPython's test module that is designed for internal use. Slim Docker images don't include this module, therefore the tests would fail to run.
=> Fix a unit test bug on slim Python Docker images

AUTHORS, hy/cmdline.py
Currently when in the hy REPL, when the user types ```help```, the REPL responds with the default builtins.help message ```Type help() for interactive help, or help(object) for help about object.``` This is inconsistent with the syntax of Hy and other REPL features, as ```quit``` and ```exit``` both display the proper syntax in their respective REPL messages.
This fix adds a ```HyHelper``` class for ```help``` similar to the ```HyQuitter``` class used to override the ```quit``` and ```exit``` builtins. Besides the corrected prompt using Lisp-like syntax, after executing ```(help)``` the user is still dropped into the default PyDoc help environment with normal Python syntax and links to documentation.
=> Fix help message in REPL

NEWS.rst, docs/language/internals.rst, hy/cmdline.py, hy/errors.py, hy/models.py, setup.py, tests/test_models.py
Closes #1820. Not particularly exciting, though I think in some aspects the code actually ends up a tad cleaner than before.
Reason for using colorama: all clint was really used for was color, and colorama is a popular, well-supported, and battle-tested library for handling this.
=> Drop clint for colors in favor of colorama

docs/language/interop.rst, docs/style-guide.rst
The quotes aren't germane, the koan is inscrutable, the design philosophy is out of date, and the conclusion is filler.
=> Remove extraneous material from the style guide

MANIFEST.in
Fixes #1861.
This is a packaging bug that affected 0.17.0, but it's not worth backporting, because I'll be making a 0.18.0 in the next few days, anyway.
=> Include fastentrypoints in the MANIFEST

LICENSE, setup.py
Previously, the Hy files would be bytecode compiled before the
compiler's dependencies were installed. In additon, the revamped
version properly propogates the optimization level and generally is a
bit cleaner.
Fixes #1864.
This solution wasn't nearly as bad I thought. (Please forgive minor formatting issues atm, literally typed this whole thing out on a phone.)
=> Revamp the setup script's install command

AUTHORS, docs/whyhy.rst
Under the [Hy versus other Lisps](https://docs.hylang.org/en/stable/whyhy.html#hy-versus-other-lisps) section, and inside the definition of the `HelloWorld` class, the `#@` tag macro is misplaced inside the parenthesis.
=> Fix misplaced `#@` tag macro

AUTHORS, NEWS.rst, docs/language/core.rst, hy/core/language.hy, tests/native_tests/core.hy
* Update argument spec parse logic of parse-args function.
* Update test case of parse-args function.
* Update document of parse-args function.
* Describe the change in NEWS file.
* Add name to AUTHORS file.
=> Fixes #1875: parse-args requires values to be representable as Hy models

AUTHORS, NEWS.rst, docs/extra/anaphoric.rst, hy/extra/anaphoric.hy, tests/native_tests/extra/anaphoric.hy
Resolves #1883
I would encourage reviewers to look at the commit history to see if there is any merit in the an earlier more verbose approach I took.
This is my first time committing lisp code, so any feedback would be kindly received! :)
=> Reduce scope of symbol replacement for anaphoric macros

AUTHORS, conftest.py, hy/__main__.py
Could we remove `imp` to avoid the deprecation message if we use `python -m hy`.
```
/usr/local/lib/python3.7/site-packages/hy/__main__.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
```
Also, [since pytest 5.4, node construction is also deprecated in favor of `.from_parent`](https://docs.pytest.org/en/latest/deprecations.html#node-construction-changed-to-node-from-parent), old style will generate deprecation warning every time when we run `pytest`
```
conftest.py:48
/.../conftest.py:48: PytestDeprecationWarning: direct construction of Module has been deprecated, please use Module.from_parent
pytest_mod = pytest.Module(path, parent)
```
=> Remove imp to avoid the deprecation message

get_version.py
Without this change, hy is not capable of figuring out the correct
version in the REPL if the version was set using the HY_VERSION
environment variable during build.
---
Seems like I missed this in #1821 (sorry!).
=> get_version.py: Also write VERSIONFILE when HY_VERSION env is set

AUTHORS, NEWS.rst, hy/macros.py, tests/importer/test_importer.py
A tiny brute-fix for #1911. I really don't know what's the root of the problem, though, but it seems to be dynamic typing letting odd stuff in and causing havoc!
=> Fix `hy.eval` from Python failing on `require`

docs/language/api.rst, docs/style-guide.rst, docs/tutorial.rst
- `documention` -> `documentation`
- `mulitple` -> `multiple`
- `arugments` -> `arguments`
=> Fix a few minor spelling mistakes

NEWS.rst, hy/models.py, tests/native_tests/language.hy
Fixes #1754.
Replaces #1923, because @brandonwillard vetoed removing `__slots__`.
Pickling `Result` with pickle protocol 0 will still fail, but this class is only for internal use and we have no intention of pickling it, so that's not a problem.
=> Add `__setstate__` and `__getstate__` to HyKeyword

NEWS.rst, hy/compiler.py, tests/compilers/test_ast.py
=> Guard against malformed `setv` in `_rewire_init`

docs/contrib/pprint.rst
There is a small typo in docs/contrib/pprint.rst.
Should read `extended` rather than `exteneded`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, exteneded -> extended

tests/native_tests/language.hy, tests/resources/__init__.py, tests/resources/pydemo.hy, tests/test_hy2py.py
#1931 is a prerequisite, since these tests fail on Python 3.5.
=> Add async tests to `pydemo`

AUTHORS, docs/language/index.rst, docs/language/interop.rst, docs/language/repl.rst
Closes #1943 
Added `repl.rst` after `cli.rst`, and documented the recent results and recent error values. I also gave a (very) brief overview of the REPL itself, as I thought it should be there - let me know if it's at all erroneous.
=> Documents *{1,3} and *e

NEWS.rst, hy/models.py, tests/macros/test_macro_processor.py
Fixes #1944.
The AST nodes coming out of the `#@` expansion had a line/column number of 0 because of how "default" HyObject properties were being handled, causing an index underflow.
This change patches HyObjects to handle default properties better (and also changes the default info to 1 to prevent any future underflow bugs).
`wrap_value()` in `models.py` initialized `HyObject`s with 0'd out source locations, causing `HyObject.replace()` to not update these objects with the proper source locations later as it looks like they're already set.
I added a `__getattr__` method to `HyObject` so that it can return a default value for these properties if they're not yet set, while still allowing them to be overridden if they have not truly been initialized.
=> Fixes #1944: macro-expanded ast nodes had bad lineno/col info

AUTHORS, NEWS.rst, docs/contrib/destructure.rst, docs/contrib/index.rst, hy/contrib/destructure.hy, tests/native_tests/contrib/destructure.hy
Closes #1936.
Builds on #1328.
Mainly updated old syntax and refactored some of the code, but the main ideas are essentially the same.
Also added `defn+`, `fn+`, and `let+` macros, which have clojure-style destructuring within their arguments.
=> Add clojure style destucturing

.travis.yml, setup.py
I'm guessing this was just an oversight? :sweat_smile:
I thought about adding 3.10 here as well, but we've seen bad mojo in the past from claiming to support the alphas too soon and then seeing breaking changes before release. :grimacing:
(Happy to adjust and include 3.10 though if that's what maintainers prefer! :heart:)
=> Add Python 3.9 to supported versions in setup.py

NEWS.rst, hy/contrib/walk.hy, tests/native_tests/contrib/walk.hy
Current implementation of ``smacrolet`` from ``hy.contrib.walk`` has a simple fault: it has an ``&optional`` argument before ``&rest``, hence when the optional ``module-name`` isn't provided, it throws an error.
```hy
hy 0.19.0+36.g14b17afd using CPython(default) 3.9.1 on Linux
=> (require [hy.contrib.walk [smacrolet]])
import hy.macros
hy.macros.require('hy.contrib.walk', None, assignments=[['smacrolet',
'smacrolet']], prefix='')
None
=> (smacrolet [a b] (+ a ((fn [a] (inc a)) 1)))
File "stdin-dad2257d93a1a88c4c55229a701f11d0767b0201", line 1, in <module>
(smacrolet [a b] (+ a ((fn [a] (inc a)) 1)))
File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
self.gen.throw(type, value, traceback)
File …
```
=> Fix and add tests for ``smacrolet``.

AUTHORS, NEWS.rst, hy/__init__.py, hy/compiler.py, hy/contrib/hy_repr.hy, hy/lex/parser.py, hy/model_patterns.py, hy/models.py, tests/native_tests/contrib/walk.hy, tests/native_tests/extra/anaphoric.hy, tests/native_tests/language.hy
Hopefully not too intrusive of a PR, but it's a breaking change.
Introduces two new `HySequence` nodes: `HyFComponent` and `HyFString`.
f-strings are now parsed as `HyFString`s, allowing routines like `walk` and `recur-sym-replace` to descend into expressions within f-strings.
This fixes #1843 and fixes #1938, and I added some tests to ensure no regressions for either.
This also tangentially affects #1948, as the relevant f-string format parsing has been relocated to `lex/parser.py`.
=> Walkable f-strings

NEWS.rst, hy/core/bootstrap.hy, hy/lex/parser.py, tests/native_tests/native_macros.hy, tests/test_lex.py
Two relatively minor bugfixes, with regression tests. No associated open issues (that I'm aware of).
Let me know if I should split this into two commits / two PRs.
=> Fixes 'J' being parsed as a complex and fixes error messages for bad `defmacro` names

NEWS.rst, hy/core/macros.hy, tests/native_tests/core.hy
Closes #1946.
Adds call to `mangle` in the doc macros so that they work with names such as `->`.
=> Make `doc` and `#doc` work with mangling

AUTHORS, NEWS.rst, docs/language/repl.rst, hy/completer.py, tests/test_completer.py
Closes #1833
Adds setting of the location of the history file to the value of the `HY_HISTORY` environment variable in the `completion` context manager, if provided.
=> Custom history location

NEWS.rst, hy/compiler.py, tests/compilers/test_ast.py
Hy compiler would crash on a root with multiple dots in a row:
```
=> (.. "crashme")
File "/home/scauligi/workspace/hy/venv/bin/hy", line 12, in <module>
sys.exit(hy_main())
File "/usr/lib/python3.9/code.py", line 232, in interact
more = self.push(line)
File "/usr/lib/python3.9/code.py", line 258, in push
more = self.runsource(source, self.filename)
File "/usr/lib/python3.9/code.py", line 63, in runsource
code = self.compile(source, filename, symbol)
File "/usr/lib/python3.9/codeop.py", line 178, in __call__
return _maybe_compile(self.compiler, source, filename, symbol)
hy.errors.HyCompileError: Internal Compiler Bug 😱
```
This fixes that.
=> Fix compiler crash on malformed `.` special form

NEWS.rst, docs/language/syntax.rst, hy/lex/parser.py, tests/native_tests/language.hy
Closes #1948 
I didn't think it was necessary to add documentation as it's part of Python, let me know if you think otherwise.
=> Add handling for "=" syntax in f-strings

NEWS.rst, docs/cheatsheet.json, docs/language/internals.rst, docs/language/model_patterns.rst, docs/language/syntax.rst, hy/contrib/destructure.hy, hy/contrib/walk.hy, hy/core/language.hy, hy/models.py, tests/native_tests/core.hy, tests/native_tests/language.hy
=> Calling HyKeyword now looks up by string name, also remove `name` from hy.core

NEWS.rst, docs/language/repl.rst, hy/cmdline.py
Adds repl init scripts with `HYSTARTUP` env var. Closes #1832  
I think we should merge #1955 before this so that the `Configuration` heading in `repl.rst` is set properly.
=> Add: HyRepl Init script loading

CONTRIBUTING.rst
#1508 has been a big success. Whereas perfectly good PRs once sat unmerged for months because nobody other than the author could get around to reviewing them, now an uncontroversial change can get merged in at worst 2 weeks. Still, 2 weeks is a while, and I've yet to see such a long interval produce late objections or vetos to a change. In all the cases over the past few years in which a PR was objected to or changes were requested, the objection came within a day or two of the PR's creation. So after the first few days, all the waiting does is slow down an inevitable merge. Faster merges would not only allow bug fixes and new features to become available more quickly; it would also encourage new Hy developers to make more PRs because of the warm fuzzy feeling of prompt integration of …
=> Policy: change the interval for uncontroversial merges to 3 days

NEWS.rst, hy/core/macros.hy, tests/native_tests/core.hy
These are syntactic sugar for `for` loops when you don't need the loop variable for anything. I thought of naming one of them `dotimes`, but I decided it would be needlessly confusing because of the differences from Common Lisp's `dotimes`.
=> Add macros `do-n` and `list-n`

NEWS.rst, docs/api.rst, docs/cheatsheet.json, hy/contrib/slicing.hy, tests/native_tests/contrib/slicing.hy
Adds macros for easy numpy/pandas style multi-index slices. Closes #541 
Seemed odd that multi index slicing is as cumbersome as it is in Hy given how prevalent it is in numpy and pandas, especially when an elegant solution was already put forth by guanyilun in that issue so this brings that in as a contrib module with some additional changes to make it more robust and cover some other cases like pandas string index slicing. I also changed the name from ``nget`` to ``ncut`` since that seemed closer to how ``cut`` works than ``get``.
=> Contrib: Multi-Index slicing macros

NEWS.rst, hy/compiler.py, tests/native_tests/language.hy
=> Prevent more ways to assign to constants

NEWS.rst, docs/cheatsheet.json, hy/core/macros.hy, tests/native_tests/core.hy
Closes #867 
This is a pretty common idiom that python even has its own sugar for so I think it makes sense to add to core. 
This should probably be grouped next to the other comprehension forms in docs, but isn't possible right now in sphinx hydomain. Once we have the new `defn` args syntax nailed down, i'll go and push an update to `hydomain` to fix all the stuff we've broken in master and give us more control on the organization of the api autodocs.
=> Feature: Add callable for macro to core

NEWS.rst, hy/_compat.py, hy/cmdline.py, hy/core/language.hy, setup.py, tests/native_tests/language.hy, tests/native_tests/native_macros.hy
Python 3.9 added `ast.unparse`, which can do most of the work. It has some bugs that I fixed in `astor`, which I've worked around here, but I've submitted a patch to CPython to fix them for real (python/cpython#24897).
=> Remove the dependency on astor for Pythons ≥ 3.9

NEWS.rst, hy/macros.py, tests/native_tests/language.hy
Fixes #1897.
I started with of with @jams2's patch, but that didn't allow for multiple "." in the source module. This should work with any valid relative path.
=> Fixed relative import for `require` and added tests

NEWS.rst, hy/macros.py, tests/native_tests/language.hy
Fixes #2016.
Also gets rid of error `HyRequireError` when requiring a module with no macros, since previously this behavior was inconsistent and I don't see why this should be an error. So previously
```hy
i => (require os.path)
i => (require [os [path]])
File "stdin-08ce82c15e0a77ce6e17125ffa2f87a3fbdcd4df", line 1, in <module>
(require [os [path]])
hy.errors.HyRequireError: The module <module 'os' from '/usr/lib/python3.9/os.py'> has no macros or tags
```
But now the second will also not throw an error.
=> Allow expressions such as `(require [hy.contrib [walk]])`

NEWS.rst, hy/cmdline.py, tests/resources/relative_import_compile_time.hy, tests/test_bin.py
Set `sys.path` correctly in `hy2py` and `hyc`. Also refactor the path-setting code a little.
=> Fix #2021: hy2py cannot import local module

hy/cmdline.py, tests/importer/test_importer.py
Turns out `exec_module` requires the module be supplied as an argument; this broke HYSTARTUP after #1989.
Also fixes a test that was incorrectly passing.
=> Fix `exec_module` usage

NEWS.rst
Typically I do a release every six months, but Hy has been moving so fast now (which I'm quite pleased about, I hasten to add—excellent work, folks) that I'd like to do an earlier release to help ease the pain of transition. Probably there will be another one around the middle of 2021.
I need two approvals from @hylang/core to do this. If I get them, I'll clean up NEWS and make the release.
=> Release Hy 1.0a1

CONTRIBUTING.rst, README.md, docs/index.rst, issue_template.md
We won't be able to close issue #1778 until we actually archive the channels, but lets update the docs and give it another month to let people filter over.
=> Docs: Migrate to github discussions

conftest.py, hy/cmdline.py, tests/resources/hystartup.hy, tests/test_bin.py
closes #2029 also fixes macros not being able to find the hystartup module causing it to error out.
=> Fix: hystartup affects tests

NEWS.rst, hy/_compat.py, hy/cmdline.py, hy/compiler.py, hy/macros.py, tests/test_bin.py
Fixes #2004 (and #2014).
The Hy REPL saves exceptions locally so that it can remove internal stack frames.
SyntaxErrors weren't getting saved, and so the REPL would instead
should the previous saved error.
This is now fixed.
Also removes `reraise()` from `hy._compat` since we're no longer supporting Python 2,
which simplifies some of the exception handling code throughout.
=> Properly handle/display SyntaxError in Hy REPL

NEWS.rst, docs/api.rst, hy/compiler.py, hy/contrib/destructure.hy, hy/contrib/sequences.hy, hy/contrib/slicing.hy, hy/contrib/walk.hy, hy/core/bootstrap.hy, hy/core/macros.hy, hy/extra/anaphoric.hy, tests/native_tests/comprehensions.hy, tests/native_tests/contrib/sequences.hy, tests/native_tests/contrib/test_pprint.hy, tests/native_tests/language.hy, tests/native_tests/model_patterns.hy, tests/native_tests/native_macros.hy, tests/native_tests/quote.hy, tests/resources/bin/main.hy
Fixes #2038. `cut` with one index now specifies the _stopping_ index.
Thus `(cut x n)` translates to `x[:n]` now instead of `x[n:]`.
This is consistent with `slice`: `(= (slice n) (slice None n))`.
=> Make unary `cut` consistent with `slice`

docs/api.rst
There is one use case missing from the annotation documentation (`^`).  For example, the following Python definition:
``` python
def add1 (x: int) -> int:
return x + 1
```
Can be translated to Hy as follows:
``` hy
(defn add1 ^int [^int x]
(+ x 1))
```
The placement of the return type annotation does not conform to the documented rules, so it can be difficult to find or even confusing for users.  Given that function return type annotation is a very common use case, I think it should be more directly exposed through the documentation.
=> Document the function return annotation

NEWS.rst, hy/contrib/hy_repr.hy
closes #1873 namedtuple's are handled by moving the `_fields` check from the `tuple` repr function to `_base-repr` which seems to work just fine
=> Fix: hy-repr won't use the registered function of a supertype

NEWS.rst, hy/cmdline.py, tests/resources/spy_off_startup.hy, tests/test_bin.py
This lets `spy` or `repl-output-fn` values set at the cmdline take precedence over those set in `HYSTARTUP`. Note though that if you set `spy` to `True` in `HYSTARTUP` there's no way to set it back to `False` since `--spy` is a truthy check and changing the cmdline args to allow it would be overkill for something you'd only really do to debug anyways.
=> Add: let hy cmdline args overwrite HYSTARTUP values

NEWS.rst, hy/compiler.py, hy/lex/parser.py, hy/models.py, tests/test_models.py
- Closes #1117.
- Closes #1617.
I couldn't think of a use case for Symbol or Keyword objects that you couldn't create with actual symbols or keywords. When you think of yourself wanting to use one of those, from analogy to other Lisps, you should probably be using plain strings instead. So, why not just make everybody's lives easier by banning them altogether? Bam.
=> Enforce syntax in Symbol and Keyword constructors

docs/api.rst, docs/cheatsheet.json, docs/conf.py, requirements-dev.txt
Closes #2068 
* Added descriptions to Core and Additional modules that explain
importing/requiring non core methods/macros
* pinned sphinx to 3.5.4 as hydomain doesn't support > 4.0 yet
made some changes to hydomain so that tag macros show up correctly and 
macros now are prefixed with `macro` so that you know that you need to `require` them
instead of `import` them at a glance
=> Fix: Manual is missing module names

NEWS.rst, docs/api.rst, docs/cheatsheet.json, docs/language/internals.rst, docs/language/syntax.rst, hy/__init__.py, hy/compiler.py, hy/contrib/destructure.hy, hy/contrib/slicing.hy, hy/contrib/walk.hy, hy/core/hy_repr.hy, hy/core/language.hy, hy/core/macros.hy, hy/extra/anaphoric.hy, hy/extra/reserved.hy, hy/lex/__init__.py, tests/native_tests/contrib/destructure.hy, tests/native_tests/contrib/slicing.hy, tests/native_tests/contrib/test_pprint.hy, tests/native_tests/contrib/walk.hy, tests/native_tests/core.hy, tests/native_tests/hy_repr.hy, tests/native_tests/language.hy, tests/native_tests/mangling.hy, tests/native_tests/model_patterns.hy, tests/native_tests/native_macros.hy
this removes `read-str`, `read`, `eval`, `mangle`, `unmangle`, `disassemble`, `macroexpand`, `macroexpand-1`, and `gensym` from builtins injection and moves them under the root `hy` module if they weren't already there.
=> Feature: qualify critical funcs under hy

docs/cheatsheet.json
Fixes the spelling of the word 'arithmetic' in the cheatsheet page of the documentation.
=> Docs: fix typo in cheatsheet.json

NEWS.rst, docs/api.rst, hy/contrib/walk.hy, hy/core/language.hy, tests/native_tests/language.hy
I didn't end up making `calling-module` private because `contrib.walk` uses it, but i did remove it from autodocs and builtins injection.
=> Clean: make 'calling-module' & 'calling-module-name' internal to hy

NEWS.rst, hy/__main__.py
Fixes #2069.
The previous code in `__main__.py` let you run files (e.g. `python -m hy script.hy`) but did
nothing when given no arguments.
The new code just runs `hy_main()` and lets it handle everything, so it's
equivalent to running the `hy` command.
=> Run REPL using `python -m hy`

NEWS.rst, docs/api.rst, docs/language/syntax.rst, hy/compiler.py, tests/native_tests/language.hy
closes #1765 
this one is actually pretty minimal and didn't break anything in any real way. One thing to note though is that while `(:from {"from" 1})` won't syntax error its still a key error since `Keyword.__call__` is defined as `return data[mangle(self.name)]` do we still think that's okay given this change?
=> Fix: dissallow python reserved words as parameters or func kwargs

NEWS.rst, docs/api.rst, docs/cheatsheet.json, hy/__init__.py, hy/compiler.py, hy/contrib/loop.hy, hy/contrib/walk.hy, hy/core/hy_repr.hy, hy/macros.py, hy/model_patterns.py, hy/models.py, tests/macros/test_macro_processor.py, tests/native_tests/contrib/destructure.hy, tests/native_tests/contrib/walk.hy, tests/native_tests/language.hy, tests/native_tests/mangling.hy, tests/native_tests/operators.hy, tests/native_tests/quote.hy, tests/test_lex.py, tests/test_models.py
closes #1363 
* models are no longer equal to equivalent python literals
* models only equal to models of the same kind
* renamed `wrap_value` -> `as_model` and exposed under `hy` module
=> Fix equality for Hy models

NEWS.rst, conftest.py, hy/compiler.py, tests/native_tests/sub_py3_7_only.hy
closes #2090 
easy money 
attempting to `setx` on Python 3.7 will result in 
```clojure
hy 1.0a1+136.gbeee3586.dirty using PyPy(51efa818fd9b) 3.7.10 on Linux
=> (setx x 1)
File "stdin-12a3a753791edb1e67c4fba15af57553319e7498", line 1, in <module>
(setx x 1)
File "<stdin>", line 1
(setx x 1)
^
hy.errors.HySyntaxError: setx is not supported on Python versions before Python 3.8
```
=> Fix: Syntax error special forms on unsupported python versions

NEWS.rst, conftest.py, docs/api.rst, docs/cheatsheet.json, docs/language/internals.rst, hy/contrib/destructure.hy, hy/contrib/loop.hy, hy/contrib/pprint.hy, hy/contrib/sequences.hy, hy/contrib/slicing.hy, hy/contrib/walk.hy, hy/core/hy_repr.hy, hy/core/language.hy, hy/core/macros.hy, hy/extra/anaphoric.hy, tests/compilers/test_ast.py, tests/native_tests/contrib/destructure.hy, tests/native_tests/contrib/walk.hy, tests/native_tests/core.hy, tests/native_tests/extra/anaphoric.hy, tests/native_tests/extra/reserved.hy, tests/native_tests/language.hy, tests/native_tests/model_patterns.hy, tests/native_tests/native_macros.hy, tests/native_tests/operators.hy, tests/native_tests/with_test.hy, tests/test_bin.py
I wasn't sure which of these to delete and which to move to the spin-off library. It's one of those things where it's hard to draw the line between useful syntactic sugar and an endless parade of tiny functions. Ultimately I just decided to trash all of them.
=> Remove core predicate functions

setup.py
These are defined in PEP 508: https://www.python.org/dev/peps/pep-0508/#environment-markers
The current implementation means that installing 1.0a2 from the published wheel on Python 3.8 does not include `astor` (and thus does not work) because "the Python version that is building the wheel is different from the Python version that is installing it" (from https://hynek.me/articles/conditional-python-dependencies/).
I don't think Windows and Linux can share wheels, so `pyreadline` doesn't strictly have to be included here, but it seems more correct to use this method for both.
(Refs https://github.com/hylang/hy/commit/06f34b018e8bab6170c6a72c4a6e25201268cdb6 / https://github.com/hylang/hy/pull/1999)
=> Use "environment markers" for conditional install_requires

NEWS.rst, hy/completer.py, setup.py
Closes #2114
This is a bit hacky, but I'm not sure if there's a better way.  I'm confident on the `setup.py` change to avoid even installing `pyreadline` on Python 3.10+ (which in itself is enough to fix the problem since then the fallback happens properly), but I added more code to handle the `AttributeError` for cases where `pyreadline` gets installed separately and thus `import readline` still pulls it in (I'm not sure which cases actually invoke the `import pyreadline` fallback code -- maybe older versions of `pyreadline`?  older versions of Python's built-in `readline` module?).
=> Handle pyreadline failure (Windows + Python 3.10+)

NEWS.rst, hy/contrib/walk.hy, tests/native_tests/contrib/walk.hy
=> Keep `let` from duplicating lambda lists

hy/core/result_macros.py
No user-visible changes, just a pet peeve of mine.
This makes quote forms such as `(a ~b ~@c)` compile to the somewhat simpler
```python
hy.models.Expression([hy.models.Symbol('a'), b, *(c or [])])
```
instead of the more complex
```python
hy.models.Expression([] + [hy.models.Symbol('a')] + [b] + list(c or []))
```
I don't think it actually affects anything, but all those unnecessary array additions were getting to me, especially on longer quoted forms.
=> Compile "quote" forms more compactly

setup.py
In #2121, I broke installation. `pip install -e` works, as we use in GitHub Actions for testing, but not without `-e`, because then `Install.__compile_hy_bytecode` runs, which tries to call `importlib.util.cache_from_source` with a nonexistent keyword argument `optimize` (a typo for `optimization`). The `cache_from_source` call was never previously executed because the glob `"hy/**.hy"` matched nothing (what was meant was `"hy/**/*.hy"`) until I added `hy.pyops`. If fixed, this code still wouldn't help, because `cache_from_source` just returns a path, without compiling anything. In short, I don't think #1865 ever really worked.
Rather than try to fix bytecode compilation, I've just removed the custom `Install` class, which makes `pip install` without `-e` work again. #1747 can be regarded …
=> Get Hy installing again

hy/_compat.py, hy/errors.py, tests/importer/test_importer.py, tests/resources/importer/compiler_error.hy
closes #1693 
don't think this really merits a NEWS update. it doesn't affect users in any real way
=> Fix: filter internal importlib frames from stacktrace

NEWS.rst, hy/core/hy_repr.hy, hy/models.py, tests/native_tests/hy_repr.hy, tests/test_models.py
Also fixes a bug where FStrings models lost `brackets` information
after going through `as_model`.
=> properly format bracketed strings in hy-repr

hy/compiler.py, hy/errors.py, hy/lex/__init__.py, hy/macros.py
eat your broccoli kids :broccoli:
=> Clean up/Normalize docstrings

AUTHORS, NEWS.rst, hy/models.py, tests/test_models.py
Closes #2153.
In relation to `List`s and `Dictionaries`, this edit tracks parents of the elements to raise a `HyWrapperError` instead of relying Python being incapable of infinite recursion for recursive models.
This is done by passing an array of already seen parents for each recursive transformation in a List or a Dict.
Mysteriously, this breaks `tests/importer/test_importer.py::test_import_error_cleanup` as the imported module raises a `NameError` and not a `HyMacroExpansionError`.
=> Detecting cycles in `as_model` from `hy/models.py`

AUTHORS, hy/core/result_macros.py, setup.py
**Update:** I've created a new PR from a separate branch, as requested in #2163, and added an entry into AUTHORS. In the first PR I occasionally skipped these steps after my first quick look at CONTRIBUTING.rst.
Although I intended to make funcparserlib 1.0.0a0 backwards-compatible with 0.3.6, there is one incompatibility detected by the Hy tests, so I had to update `importlike(...)` to account for these changes.
`p1 + maybe(skip(p2))` no longer returns the result of `p1` if `p2` matches its tokens, so `skip(...)` it not distributive. The funcparserlib docs for 0.3.6 mentioned that you can use skip() **only** in `+`-expressions, but there is no enforcement for that. The current behaviour of `p1 + maybe(skip(p2))` is `(<the parse result of p1>, _Ignored(<the parse result of p2>))`.
=> Upgrade to funcparserlib 1.0.0a0

.github/workflows/tests.yml, NEWS.rst, hy/__init__.py, hy/_compat.py, setup.py, tests/native_tests/hy_repr.hy, tests/native_tests/sub_py3_7_only.hy
[Python 3.6 reaches its end-of-life on December 23rd.](https://devguide.python.org/#status-of-python-branches) So, removing support is appropriate for a release in January or the last few days of the year.
=> Remove Python 3.6 support

docs/api.rst
Fixes #2157. (I searched for `{:` and the only other instance I found was in the style guide, where it doesn't make a difference.)
=> Fix a doc example for keyword-call changes

docs/hacking.rst
Just in case a new contributor is not aware of the migration to
libera.chat.
=> Removed IRC server in favor of GH Discussions

NEWS.rst, docs/api.rst, docs/cheatsheet.json, docs/whyhy.rst, hy/compiler.py, hy/core/result_macros.py, hy/scoping.py, tests/compilers/test_ast.py, tests/native_tests/comprehensions.hy, tests/native_tests/let.hy, tests/native_tests/py3_10_only_tests.hy, tests/native_tests/py3_8_only_tests.hy
Once again, a major breaking change that nobody asked for, even though I haven't even finished the last one.
Here's a (draft) implementation that adds tracking of scoping information, allowing us to implement `let` as a first-class result macro.
I did my best to have `let` bindings interact nicely with Python's normal scoping rules; that is, let bindings are as close to possible as standard assignment.
This example is fairly straightforward; `x` refers to the name outside the function.
```hy
(let [x 1]
(defn foo []
(print x)))
(foo)
```
```python
_hy_scope_1_x = 1
def foo():
return print(_hy_scope_1_x)
foo()
```
If we assign to `x` inside the function, then per Python scoping rules, `x` is entirely local to the function despite any assignment outside:
```python
x = 1
def foo():
print(x) …
```
=> yet another let implementation

setup.py
When adding `hy` as a `git` depedency with Poetry, it tries to read `setup.py` and crashes because `os` is not imported
=> Add "import os" in setup.py

LICENSE, NEWS.rst, setup.cfg
I've decided that the right order of operations is to release Hy first and Hyrule second, because Hyrule depends on Hy and not the reverse. But the goal is to be practically simultaneous, so I wouldn't merge this before Hyrule was ready, too.
=> Release Hy 1.0a4

docs/whyhy.rst
Just found out by accident that CherryPy website changed, I replaced it with the Github repo, I guess it should be more "stable"
=> Typo in docs: CherryPy link

CONTRIBUTING.rst
The Makefile was removed in 0169ffa47563b0e5940912754a32bbb7b712202a.
=> Remove reference to `make d`

docs/api.rst, docs/cheatsheet.json, docs/language/internals.rst, docs/language/repl.rst, docs/tutorial.rst, hy/core/util.hy, tests/native_tests/comprehensions.hy
Closes #2194.
All of this is documentation edits, except for one commit that adds new tests to match new statements about `break` and `continue` in the documentation.
=> Documentation tweaks

docs/_templates/layout.html, docs/conf.py
closes #2219 
Adds `has_active_alpha` bool we can toggle off when we're not in an alpha cycle and don't need the warning
=> Docs: Add stable branch warning header for active alpha cycle

NEWS.rst, hy/core/result_macros.py, hy/model_patterns.py, hy/models.py, tests/native_tests/py3_10_only_tests.hy
Something i noticed fiddling around today. 
Hy would crash when trying to pattern match against keywords
```clojure
(match :hello
:hello 1
:world 2)
=> hy.errors.HySyntaxError: parse error for pattern macro 'match': got unexpected token: :hello, expected: end of file
```
Turns out I forgot that Keywords are compiled into a class instantiation calls not values and need to be handled as such.
=> Fix: crash when using keywords as match value

NEWS.rst, docs/api.rst, hy/scoping.py, tests/native_tests/comprehensions.hy, tests/native_tests/let.hy
- Fixes #2224.
- Replaces #2228.
=> Fix scoping in comprehensions in `let`

NEWS.rst, conftest.py, docs/api.rst, hy/core/macros.hy, hy/core/result_macros.py, hy/macros.py, tests/native_tests/language.hy, tests/resources/exports.hy, tests/resources/exports_none.hy
- Closes #1934 
- Closes #2142
I thought `eval-and-compile` would be necessary for setting `_hy_export_macros`, but of course, by the time you're requiring a module, the whole thing has been executed.
=> Add `_hy_export_macros` and `export`

NEWS.rst, hy/core/macros.hy, hy/macros.py, tests/native_tests/native_macros.hy
closes #1689 
adds a `RuntimeWarning` when a user attempts to redefine a core macro and a new core macro `delmacro` a macro equivalent of `del` that deletes macros in the calling namespace. 
So the case of redefining `require` would look like:
```clojure
=> (require tests.resources.tlib [qplah])
hy.macros.require('tests.resources.tlib', None, assignments=[['qplah', 'qplah']], prefix='')
None
=> (defmacro require [] 1)
<string>:1: RuntimeWarning: require already refers to: `require` in module: `builtins`, being replaced by: `__console__.require`
(defmacro require [] 1)
hy.macros.macro('require')(lambda hyx_XampersandXcompiler: 1)
None
=> (require)
1
1
=> (delmacro require)
None
=> (require tests.resources.tlib [parald])
hy.macros.require('tests.resources.tlib', None, …
```
=> delmacro and macro redefinition warning

docs/api.rst, hy/core/result_macros.py, hy/macros.py, tests/native_tests/reader_macros.hy, tests/resources/tlib.hy
Closes #2265.
Breaks latest hyrule since the API for `hy.macros.require_reader` is slightly different, but it's a very easy fix.
I can submit a PR once this one goes through.
=> Allow `(require ... :readers *)`

hy/cmdline.py, tests/resources/hystartup.hy, tests/test_bin.py
Allows reader macros to be defined/required in the $HYSTARTUP file and be available in the REPL.
=> Load reader macros from $HYSTARTUP

hy/lex/hy_reader.py, tests/native_tests/language.hy
hy reader wasn't properly parsing expressions after `^`
=> Fix: subscript type annotations

NEWS.rst, docs/api.rst, hy/core/result_macros.py, tests/native_tests/native_macros.hy
closes #1730 
`defmacro` no longer allows the position only delimiter `/` (values are always passed positionally), the keyword only delimiter `*`, kwargs  `#** kwargs`, or arguments after an `#*` args as part of it's parser.
=> narrow defmacro lambda list parser

hy/models.py
=> Remove `Keyword.__slots__`

.gitignore, NEWS.rst, setup.py
Change setup.py to generate .pyc files from .hy files on install (which will cause setup.py to include them in wheel distributions as well).
Fixes #1747; a similar patch to hyrule's setup.py will fix https://github.com/hylang/hyrule/issues/42. I can't test rpm/deb/etc generation, but with the way this generates the source/wheel distributions it should fix the .pyc recompilation issue regardless of the end package manager.
Note that this now makes wheels specific to a python version (ie instead of `hy-0.21-py3-none-any.whl`, running `setup.py bdist_wheel` will now generate `hy-0.21-cp310-none-any.whl`)
So for Pypi we (really, @Kodiologist) will want to generate wheels for each version of python we support. The source distribution doesn't contain .pyc files so it's still version agnostic.
=> Generate .pyc files from .hy files on install

docs/api.rst, docs/syntax.rst, docs/tutorial.rst, docs/whyhy.rst
=> Documentation improvements

NEWS.rst, hy/reader/hy_reader.py, tests/native_tests/language.hy
=> Recognize `\N{…}` escape sequences in f-strings

CONTRIBUTING.rst
Back in ye olde days of 2018 when the gist of our merge policy was implemented (#1508), there was a concern that releases deserved extra scrutiny. The way I ended up trying to address this concern, which ultimately was accepted, was to make PRs for new releases exempt from the rule that a sufficiently old PR with no objections could be merged without review.
What I've found while doing the 10 major releases since this rule change is that the exception doesn't seem to be doing any good. It can take a long time for the release to be rubber-stamped, over a month in some cases, and in the one case I can recall a new-release PR being objected to (when we were arguing about alpha releases versus 0.x releases), the whole discussion took place before the three-day deadline. So it appears that by …
=> Remove exception to the merge policy for releases

NEWS.rst, hy/importer.py, tests/importer/test_importer.py
=> Implement import from ZIP archives

docs/whyhy.rst
Update documentation example to 0.25.  #@ not supported anymore change to [] as first parameter in defn.
=> Update CherryPy example to hy0.25

AUTHORS, NEWS.rst, docs/cli.rst, hy/cmdline.py, tests/test_bin.py, tests/test_hy2py.py
- Closes #2079
hy2py currently only support single files.
This PR adds two functionality:
1. support for `output` parameter to specify where output should go for file or folder.
2. support for recursive transformation of hy files in folders. Outputs to original folder if output is not specified, follows original folder structure.
=> Add folder output for hy2py

NEWS.rst, hy/cmdline.py, hy/reader/hy_reader.py, hy/repl.py, setup.cfg, tests/native_tests/repl.hy, tests/test_bin.py
- Fixes #2427
- Fixes #2430
Both bugs were caused by the same underlying issue, which is a regression I introduced in #2412, specifically 5fb663ee5beafe0188927cf4bb23deee204bfeb4.
I've also gone further and forbid shebangs in the REPL and `hy -c` entirely, since they have no legitimate use there.
=> Fix some shebang issues

NEWS.rst, docs/cli.rst, hy/repl.py
- Closes #1435
I arbitrarily chose `'-' * 30` as the (default) delimiter. I don't have a strong preference, so if you'd like to bikeshed about it, now's the time.
=> In the REPL, print a delimiter after `spy` output

.github/workflows/tests.yml, hy/_compat.py, hy/compiler.py, hy/core/result_macros.py, hy/errors.py, hy/macros.py, tests/compilers/test_ast.py
There are still some `DeprecationWarning`s produced by pytest itself, but these should be fixed by https://github.com/pytest-dev/pytest/pull/10894.
=> Replace all uses of features that are deprecated in Python 3.12

NEWS.rst, docs/cli.rst, hy/cmdline.py, hy/core/result_macros.py, hy/macros.py, tests/compilers/test_ast.py, tests/test_bin.py
- Fixes #2204
I feel like I don't know what I'm doing, because the subtleties of loading and finding modules in Python are beyond me, but this does seem to improve things.
=> Support relative `require`s in `hy -m` and `hy2py`

NEWS.rst, hy/reader/hy_reader.py, tests/macros/test_macro_processor.py, tests/test_models.py
=> Forbid `Symbol("#foo")`

README.md
I joined Hy's core team seven years ago. By various metrics (eligible pull requests reviewed, pull requests written, commits made, lines of code changed, issues closed, releases managed, user questions answered, and hours spent on Hy development), I've since become the biggest single contributor to Hy by a substantial margin (particularly in the period after Hy's busy first two years of life). In general, I've taken on a lot of responsibility. So, I'd say I'm the de-facto lead developer. Let's make it official.
I'm not proposing I should get any special privileges, which would be pretty meaningless anyway so long as @scauligi and I are the only active developers. This is really just for my resume. Perhaps if Hy development gets a lot busier (after the release of 1.0, one could imagine), …
=> Make Kodi officially the maintainer

NEWS.rst, hy/cmdline.py, hy/compiler.py, tests/test_bin.py
Fixes a bug where `hy2py` was accidentally importing (and thus executing) the module/script being parsed.
As part of the bugfix, I also changed `hy2py` to explicitly use the `-m` flag for parsing modules, bringing it more in line with `hy`/`python` commandline flags.
It also now follows the same `sys.path` rules too, where using `-m` adds the current directory to `sys.path`, but passing a file directly adds the parent directory of the file instead.
=> hy2py now uses `-m` for modules

NEWS.rst, docs/cli.rst, hy/cmdline.py, tests/native_tests/repl.hy, tests/test_bin.py
- Closes #1395
- Closes #2413
- Closes #2438
I've checked by hand that #1395 works now, but I haven't added a test for it or mentioned it in NEWS because I don't want to suggest that we really support `pdb`. That seems like a deep rabbit hole to go down.
=> Treat `hy -i` as a flag, and allow running scripts provided through standard input

hy/cmdline.py, tests/test_bin.py
This was a regression from #2467. It looks like I foolishly didn't include a test when I originally wrote #1163.
=> Fix `hy2py` on standard input

NEWS.rst, hy/reader/hy_reader.py, tests/native_tests/strings.hy, tests/test_reader.py
Fixes #2474.
maneuvering escapes through encodings and encodings through escapes
=> Fix quotes inside bracketed f-strings

NEWS.rst, hy/macros.py, tests/native_tests/functions.hy
=> Correct `root` in pattern macros with dotted head

NEWS.rst, docs/api.rst, docs/syntax.rst, hy/core/result_macros.py, hy/core/util.hy, hy/models.py, tests/native_tests/hy_misc.hy, tests/native_tests/macros.hy, tests/native_tests/quote.hy
=> Miscellany

docs/api.rst, hy/core/result_macros.py, hy/reader/mangling.py, tests/native_tests/functions.hy, tests/native_tests/model_patterns.hy, tests/native_tests/quote.hy, tests/resources/importer/circular.hy, tests/resources/importer/foo/__init__.hy, tests/resources/importer/foo/__init__.py, tests/resources/importer/foo/some_mod.hy, tests/resources/importer/foo/some_mod.py, tests/test_bin.py
- Closes #2252
After a lot of [soul-searching](https://old.reddit.com/r/lisp/comments/15oc52i/how_does_nested_quasiquotation_work_how_should_it/) and adding a few more tests, I've decided that the way Hy does quasiquotation is correct, or at least, correct enough.
I was pointed to [a pretty thorough test suite of quasiquotation in Common Lisp](https://github.com/fare/fare-quasiquote/blob/master/quasiquote-test.lisp), but translating it to Hy looks intimidating, so I'm not going to take that on before I'm convinced that we need even more tests than what I've added here.
=> Improve quasiquote testing and docs

NEWS.rst, hy/cmdline.py, hy/compiler.py, hy/core/macros.hy, hy/core/result_macros.py, hy/importer.py, hy/macros.py, hy/reader/__init__.py, hy/reader/hy_reader.py, tests/native_tests/reader_macros.hy
- Fixes #2291.
- Fixes #2292.
`hy.read` now attaches its reader to the form it returns, so patterns like
```hy
(hy.eval (hy.read "(defreader foo 3)"))
(hy.eval (hy.read "#foo"))
```
work as expected.
If a reader can't be found, then we'll create one temporarily so that everything goes through.
=> Always have a reasonable reader accessible

hy/core/result_macros.py
Moves checked creation of Symbols and Keywords to new functions `hy.sym()` and `hy.kw()`.
Without speedsym (best of 5 runs):
```
$ time hy -c "(for [_ (range 100000)] 'a)"
real    0m0.699s
user    0m0.680s
sys     0m0.010s
```
With speedsym (best of 5 runs):
```
$ time hy -c "(for [_ (range 100000)] 'a)"
real    0m0.102s
user    0m0.086s
sys     0m0.018
```
I've been using Hy as part of an x86 instruction simulator, where we're hooking every instruction and running a bit of Hy code; the slowdown from creating Symbols (because of quoted forms) is enough to get our simulator to time out.
=> Bypass validity checks when quoting Symbols and Keywords

NEWS.rst, hy/macros.py, hy/models.py, tests/native_tests/import.hy
- Closes #2451
The manual is unchanged because this feature was never documented to start with.
=> Remove partial macro namespacing

NEWS.rst, docs/api.rst, hy/compiler.py, hy/core/macros.hy, hy/core/result_macros.py, hy/macros.py, tests/native_tests/doc.hy, tests/native_tests/hy_misc.hy, tests/native_tests/import.hy, tests/native_tests/macros.hy, tests/native_tests/macros_local.hy, tests/resources/local_req_example.hy, tests/resources/macro_with_require.hy, tests/resources/macros.hy, tests/resources/more_test_macros.hy, tests/test_bin.py
- Closes #900
I haven't added support for local macros to other parts of the language (like `hy.eval`) in lieu of a more comprehensive approach to macros as first-class objects (#1467), which I'd like to do soon. Similarly, I haven't polished the documentation because I'd like to do that as part of a larger overhaul of, and content addition for, macro-related documentation (#2484).
=> Implement local `defmacro` and `require`

docs/index.rst, docs/whyhy.rst
This is to avoid the following warnings when building the documentation
Explicit markup ends without a blank line; unexpected unindent.
=> Fix comments in the index and why Hy documents

NEWS.rst, hy/core/result_macros.py, tests/compilers/test_ast.py, tests/compilers/test_compiler.py
=> Optimize short-circuiting operators

NEWS.rst, docs/api.rst, hy/compiler.py, hy/core/result_macros.py, hy/scoping.py, tests/native_tests/let.hy, tests/native_tests/nonlocal.hy
Promote `nonlocal` declarations to `global` ones if the "nearest" matching definition is in the global scope.
Also addresses #2507; can be considered a fix if we decide that the explicit-`nonlocal` formulation is the proper way to do things.
=> Automatically promote `nonlocal` as needed

hy/core/result_macros.py, tests/compilers/test_compiler.py
Can't use `isinstance(..., BoolOp)` to check if the tracked expression is "our" boolop node or not, because the first operand might itself be a `BoolOp`.
=> Fix overzealous boolean compaction

NEWS.rst, hy/cmdline.py, hy/repl.py, tests/test_bin.py
Also sets `sys.argv` as `python3 -i <filename>` does.
=> Make `hy -i <filename>` skip shebang line

NEWS.rst, docs/syntax.rst, hy/models.py, tests/test_reader.py
=> Fix parsing of `nanJ` etc.

NEWS.rst, docs/api.rst, hy/core/result_macros.py, hy/scoping.py, tests/native_tests/functions.hy
=> Async generators no longer implicitly return final expressions

NEWS.rst, docs/macros.rst, hy/compiler.py, hy/core/macros.hy, hy/core/result_macros.py, hy/core/util.hy, hy/macros.py, tests/macros/test_macro_processor.py, tests/native_tests/hy_eval.hy, tests/native_tests/hy_misc.hy, tests/native_tests/macros_first_class.hy, tests/native_tests/macros_local.hy, tests/resources/local_req_example.hy
- Closes #1467
Now the user can list local macros and get local-macro objects. I've decided it's best not to try to implement adding or deleting local macros dynamically, since that seems messy and of dubious value. So the situation is similar to ordinary variables in Python: the global set is completely dynamic, while the local set is fixed at runtime.
[Edit: the following turned out to be easy enough, so I just added it to this PR.] Next up is allowing `hy.eval` to use local macros, perhaps as part of a general faculty to allow the user to pass in a dictionary of macros. Next, perhaps, some extensions to `hy.macroexpand` and `hy.macroexpand-1` to control what set of macros they use.
=> Add `local-macros` and extend `hy.eval` and `hy.macroexpand`

NEWS.rst, docs/api.rst, docs/conf.py, docs/syntax.rst, hy/__init__.py, hy/core/macros.hy, hy/macros.py, hy/reader/mangling.py, tests/native_tests/comprehensions.hy, tests/native_tests/deftype.hy, tests/native_tests/hy_eval.hy, tests/native_tests/hy_misc.hy, tests/native_tests/let.hy
=> Add `hy.R` and rename `hy.M` to `hy.I`

docs/api.rst, docs/macros.rst
- Closes #2484
- Closes #2390
Okay, admittedly, some other macro-related documentation throughout the manual, like the description of `defmacro`, might still need some polishing. But that's true for a lot of the manual. I intend to do it eventually.
=> Overhaul the manual's chapter on macros

.github/workflows/tests.yml, docs/tutorial.rst, setup.py
- Closes #2198
I'll also link to it from the top bar at http://hylang.org , if there are no objections.
=> Link to Infinitesimal Quest 2 + ε from the manual

docs/_static/custom.css, docs/_static/overrides.css, docs/_templates/breadcrumbs.html, docs/api.rst, docs/cli.rst, docs/conf.py, docs/hacking.rst, docs/index.rst, docs/interop.rst, docs/macros.rst, docs/semantics.rst, docs/syntax.rst, docs/tutorial.rst, docs/whyhy.rst, requirements-dev.txt
- Closes #2417
Here are various changes, in combination with a commit I just pushed to [hyhomepage](https://github.com/hylang/hyhomepage), to clean up the manual and put it on hylang.org. You can see the result at http://hylang.org/hy/doc/doc-testing.  URLs that now look like
https://docs.hylang.org/en/stable/syntax.html
will instead be
https://hylang.org/hy/doc/v0.26.0/syntax
- I use version numbers insted of `stable` and `master` because [cool URIs don't change](https://www.w3.org/Provider/Style/URI). We'll no longer provide official web versions of pre-release versions of the Hy manual, and that should no longer be terribly necessary now that Hy isn't breaking backwards compatibility so frequently. I'll redirect docs.hylang.org to the latest release.
- The file extension (`.html`) is …
=> Overhaul rendering of the manual

.isort.cfg, NEWS.rst, docs/conf.py
This is effectively a release candidate for Hy 1.0.0, since I have no specific plans for anything to do on Hy before then. If a few months pass and no new issues have come up, I may rerelease it as 1.0.0 with only changes to documentation and version numbers.
=> Release Hy 0.29.0

docs/interop.rst
=> In the manual, warn more against `__init__.hy`

NEWS.rst, hy/compat.py, hy/importer.py
=> Update `_get_code_from_file` for Python 3.12.6

.github/workflows/tests.yml, NEWS.rst, hy/compat.py, hy/compiler.py, hy/core/result_macros.py, hy/errors.py, hy/repl.py, setup.py, tests/compilers/test_ast.py, tests/native_tests/defclass.hy, tests/native_tests/macros.hy, tests/native_tests/repl.hy, tests/test_bin.py, tests/test_reader.py
=> Support Python 3.13

NEWS.rst, hy/core/result_macros.py, tests/native_tests/with.hy, tests/resources/__init__.py
- Fixes #2605
The code for `with` is now even hairier. C'est la vie. At least it's still pretty short.
=> Fix statement pull-out in multi-item `with`

NEWS.rst, docs/api.rst, hy/core/result_macros.py, tests/native_tests/try.hy, tests/native_tests/with.hy, tests/resources/__init__.py, tests/resources/pydemo.hy, tests/test_hy2py.py
This branch started out with editing `pydemo.hy` and `test_hy2py.py` for use with py2hy, but then I found an obscure bug in `try`.
=> Fix the interpretation of `except [[]]`

docs/cli.rst, docs/interop.rst, docs/tutorial.rst, tests/resources/pydemo.hy, tests/test_hy2py.py
- Closes #1721
These additions are largely in the service of py2hy.
=> Add more tests to `pydemo.hy`

NEWS.rst, docs/api.rst, hy/core/result_macros.py, tests/native_tests/setv.hy, tests/resources/pydemo.hy, tests/test_hy2py.py
@scauligi I decided it was best not to add a core macro, which would add to our already large set of core macros, for this rarely used feature.
=> Allow chained assignment in `setv`
