hylang/hy

- hy/compiler.py
- tests/native_tests/with_decorator.hy
Fix is basically copied from olasd from irc, test is mine.
> Added a fix for nested decorators. Fixes #752

- AUTHORS
- hy/cmdline.py
- hy/completer.py
Recreating #754 because I can't reopen it after squashing.
> Adapt attribute completion from IPython completer 

- AUTHORS
@berkerpeksag here you go. Hope this is fine
> Adding Shrayas to AUTHORS

- hy/_compat.py
- hy/cmdline.py
- hy/completer.py
Fixes issue introduced in #755
> Fix issues with tab completion.

- AUTHORS
- docs/language/core.rst
- hy/core/language.hy
- tests/native_tests/core.hy
`symbol?` will test if the input is an instance of HySymbol. It's useful when writing macros.
> add `symbol?` function to `hy.core`

- docs/language/api.rst
changed the specific values to make the example slightly more clear
> minor change

- AUTHORS
- docs/language/api.rst
- hy/core/language.hy
- tests/native_tests/core.hy
Hi,
This is my first PR (hopefully of many). I'm going to be working with Hy in production over the next few months and so will be hopefully be able to feed back any features I work on.
This particular addition is trivially small, but a chance to say 'hello' :cake:
> Added (last) function to core language

- hy/core/shadow.hy
- tests/native_tests/shadow.hy
> Add shadow functions for comparison operators

- hy/compiler.py
- tests/compilers/test_ast.py
- tests/native_tests/language.hy
Fixes #792. I feel like this was too easy and that I did something wrong...but it *seems* fine.
> Add argument destructuring

- hy/compiler.py
- tests/compilers/test_ast.py
Related to https://github.com/hylang/hy/issues/246
> Added `nonlocal`. `global` takes multiple args.

- docs/language/api.rst
This only makes sense once #719 gets merged.
Signed-off-by: Gregor Best <gbe@unobtanium.de>
> Add documentation for the (nonlocal ...) directive

- .travis.yml
- tox.ini
(But not codepaths, in case someone cares)
> Remove 2.6 entirely from test runners

- docs/contrib/flow.rst
- docs/contrib/index.rst
- hy/contrib/flow.hy
I've added flow macros for Hy, both the switch macro, and the guard macro.
> Added flow macros

- docs/contrib/flow.rst
- Reworded intro a bit
- Cleaned up white space
- Reworded examples
> Rework `flow' module doc

- docs/language/api.rst
- hy/compiler.py
- tests/native_tests/language.hy
@algernon Beat you to it. ;)
Ref. #844.
> Let setv take pairs of arguments

- docs/language/core.rst
- docs/tutorial.rst
- hy/compiler.py
- hy/core/language.hy
- hy/lex/parser.py
- tests/lex/test_lex.py
- tests/native_tests/language.hy
> Add one-argument division and rationals

- docs/language/core.rst
- hy/core/language.hy
- tests/native_tests/language.hy
Useful for readings stuff from strings instead of file-like objects
> Add read-str

- hy/contrib/botsbuildbots.hy
- hy/core/language.hy
- hy/core/macros.hy
- tests/__init__.py
- tests/native_tests/contrib/botsbuildbots.hy
- tests/native_tests/native_macros.hy
cute but it's getting a little in the way. i'm open to moving it to contrib too
> remove botsbuildbots

- tests/compilers/test_ast.py
- tests/native_tests/language.hy
> Add a few tests for various defn corner cases

- docs/tutorial.rst
> Add section about macros in tutorial

- hy/compiler.py
This just reuses the same temporary across nested if branches.
> Remove redundant assignments with nested ifs (closes #842)

- docs/language/core.rst
Closes #733
Signed-off-by: Csilla Nagyne Martinak <csilla@csillger.hu>
> docs: Document the (keyword) and (name) functions

- docs/contrib/anaphoric.rst
See https://github.com/hylang/hy/issues/965
I'm not used to using git collaboratively, so this might blow up your repo for all I know.
> Add import anaphoric macros info

- docs/quickstart.rst
- docs/tutorial.rst
Add the #! syntax to the quickstart guide, and to the tutorial as well. Fixes #992.
> docs: Add some documentation about #!

- AUTHORS
- hy/cmdline.py
- hy/errors.py
> Fix cmdline error to string conversion.

- README.md
this was mentioned in github.com/hylang/hy/issues/1035
> add IRC info in readme

- AUTHORS
He's had a few PRs merged now, and ought to have credit for them. :smile:
https://github.com/hylang/hy/pull/994
https://github.com/hylang/hy/pull/1012
https://github.com/hylang/hy/pull/1014
https://github.com/hylang/hy/pull/1017
> Add Jakub Wilk to AUTHORS

- CONTRIBUTING.rst
> Add doc and related link to good-first-bug tag

- docs/contrib/anaphoric.rst
- docs/contrib/loop.rst
- docs/language/api.rst
- docs/language/internals.rst
Found using [urlycue](https://github.com/jwilk/urlycue).
> Use HTTPS for Wikipedia URLs

- docs/tutorial.rst
---
docs/tutorial.rst | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
> Doc: typo (missing quote).

- docs/language/cli.rst
> doc: cli: mention `--spy` only works in REPL mode.

- .travis.yml
- hy/compiler.py
- tox.ini
From [commentary](https://github.com/hylang/hy/pull/1112#issuecomment-249065602) on #1112. This is just a guess and probably won't work.
> nightly Python on Travis CI??

- docs/quickstart.rst
> change quickstart install from PyPI to GitHub

- docs/language/api.rst
Add a comment showing the equivalent Python of the long example, and demonstrate how to get `from` and `as` on the same line.
> clarify documentation of import

- .travis.yml
Fixes the now-failing Travis @Kodiologist saw at https://github.com/hylang/hy/pull/1113#issuecomment-253047608.
> Test Python 3.6 apart from nightly

- hy/core/macros.hy
> add Clojure's as-> macro

- setup.py
Haha, I'm good at doing this quickly. :)
Closes #931. @Ketsuban Looks good?
> Add versioned entry point scripts

- hy/compiler.py
- tests/compilers/test_ast.py
> Give an error on empty attributes

- AUTHORS
- CONTRIBUTING.rst
Fixes https://github.com/hylang/hy/issues/1033
> CONTRIBUTING.rst: Add different versions of docs

- docs/language/api.rst
> Add an example of using argparse with defmain

- hy/cmdline.py
> Allow hy2py to use standard input instead of a file

- docs/contrib/index.rst
- docs/contrib/profile.rst
This PR contains basic docs for contrib.profile
fixes #1145
> Added contrib.profile docs

- AUTHORS
- hy/core/language.hy
Fix a typo, improve docstring of juxt, (thanks to @Kodiologist for the improved wording).
> Improve integer? and juxt docstrings

- docs/language/core.rst
This PR contains some updated documentation:
* Added info about included itertools and linked to Python docs
fixes #954
> Added itertools docs

- setup.py
> Include hy.extra in packaging

- NEWS
Reopening pull request, because apparently I don't know how to rebase without causing a mess :D Sorry about the hassle.
> Release 0.12.0 preparation

- CONTRIBUTING.rst
- NEWS
- docs/language/api.rst
- hy/core/language.hy
- tests/native_tests/language.hy
The documentation should now be correct (#1214).
> Make xor return single true inputs

- NEWS
- docs/language/api.rst
- docs/language/internals.rst
- hy/_compat.py
- hy/compiler.py
- hy/lex/lexer.py
- hy/lex/parser.py
- hy/models.py
- tests/compilers/test_ast.py
- tests/native_tests/native_macros.hy
Closes #495 (after a mere three years).
> Add bytestring literals

- NEWS
- tests/test_bin.py
> Add tests for #533

- docs/language/api.rst
- docs/language/internals.rst
> More documentation of strings and keywords

- NEWS
- hy/lex/__init__.py
- hy/lex/exceptions.py
- tests/test_lex.py
> Fix a crash when tokenizing a single quote

- NEWS
> Update NEWS for sharp macros

- NEWS
- hy/_compat.py
- hy/compiler.py
- hy/core/macros.hy
- hy/importer.py
- setup.py
- tests/compilers/test_compiler.py
- tests/native_tests/language.hy
- tests/native_tests/py3_only_tests.hy
> Drop support for untested versions of Python

- NEWS
- docs/language/api.rst
- hy/compiler.py
- tests/compilers/test_ast.py
- tests/native_tests/language.hy
> Improvements to `try`

- CONTRIBUTING.rst
- LICENSE
- docs/hacking.rst
Since this PR involves policy changes, it should have two reviewers.
> Overhaul CONTRIBUTING.rst

- NEWS
- setup.py
I've tested the generated packages. Merge this and I'll be ready to tag the release on GitHub and send packages to @paultag for upload to PyPI.
> Minor edits for release 0.13.0

- NEWS
- hy/importer.py
- tests/test_bin.py
Fixes #1306.
This was one of those bugs that took like 2 minutes to fix and 2 hours to write a test for. Le sigh.
> Support PYTHONDONTWRITEBYTECODE

- NEWS
- docs/language/api.rst
- hy/contrib/hy_repr.hy
- hy/models.py
- tests/native_tests/contrib/hy_repr.hy
- tests/test_lex.py
> Require capitalizing NaN and Inf like so

- setup.py
- tests/compilers/test_ast.py
Closes #1313. Ref. alex/rply#52, alex/rply#71.
> Update rply to 0.7.5

- hy/contrib/hy_repr.hy
- hy/contrib/profile.hy
> Two small bugfixes

- NEWS
- hy/importer.py
- hy/lex/lexer.py
- hy/lex/parser.py
- tests/native_tests/tag_macros.hy
- tests/test_lex.py
> Don't try to lex tag-macro calls as shebangs

- NEWS
- hy/core/shadow.hy
- tests/native_tests/operators.hy
> Shadow `get`

- NEWS
- hy/completer.py
> Save REPL history after an exception

- NEWS
- docs/conf.py
- docs/language/core.rst
- hy/compiler.py
- hy/core/language.hy
- tests/compilers/test_ast.py
- tests/native_tests/core.hy
> Implement Python 2 `exec`

- README.md
> Link to "Hacking on Hy" in the README

- NEWS
- docs/language/api.rst
- hy/compiler.py
- tests/native_tests/with_test.hy
> Initialize the return variable of `with`

- .travis.yml
- requirements-dev.txt
- requirements-travis.txt
- tox.ini
> Test PyPy3 on Travis

- NEWS
- hy/cmdline.py
- tests/test_bin.py
> Catch exceptions raised by HyREPL.output_fn

- AUTHORS
- NEWS
- hy/compiler.py
- tests/compilers/test_ast.py
- tests/native_tests/language.hy
Closes https://github.com/hylang/hy/issues/1405
> Allow else after a while loop

- NEWS
- hy/compiler.py
- tests/native_tests/language.hy
Fixes https://github.com/hylang/hy/issues/1409.
> Let argument destructuring work with docstrings

- docs/language/api.rst
- hy/compiler.py
> Refactoring and docs for eval-X-compile

- NEWS
- docs/language/api.rst
- hy/compiler.py
- tests/native_tests/language.hy
> Allow multiple expressions in a try

- NEWS
- docs/conf.py
- docs/language/api.rst
- hy/compiler.py
- tests/native_tests/language.hy
> Handle statements in the condition of `while`

- NEWS
- hy/compiler.py
- tests/native_tests/__init__.py
- tests/native_tests/language.hy
- tests/resources/tlib.py
Closes #1496 
Just need to figure out how to test this - might make sense to just inspect the emitted ast.
> Relative imports

- NEWS.rst
- docs/contrib/hy_repr.rst
- hy/contrib/hy_repr.hy
- tests/native_tests/contrib/hy_repr.hy
Reopened for the new merge policy.
> hy-repr improvements

- NEWS.rst
- hy/compiler.py
- tests/compilers/test_ast.py
- tests/native_tests/py36_only_tests.hy
- tests/native_tests/py3_only_tests.hy
- tests/test_bin.py
Fixes #855 (though I didn't think to search for the issue until after I implemented it...)
> Add metaclass support, support PEP 3115 and PEP 487

- NEWS.rst
- hy/core/macros.hy
- tests/native_tests/language.hy
- tests/resources/macros.hy
> In ->>, don't modify the arguments

- docs/quickstart.rst
Since many people came to `hy` from Python community, knowing this would be helpful for learning as well as debugging.
> Add `hy --spy` in quickstart

- docs/quickstart.rst
This is a feedback on this concern: https://github.com/hylang/hy/pull/1551#discussion_r177628810
> Make description in the quickstart more clean

- AUTHORS
@Kodiologist - 😄
---
Update: seems windows don't like me
> Add Yigong Wang to AUTHORS

- NEWS.rst
- hy/cmdline.py
- tests/test_bin.py
Closes https://github.com/hylang/hy/issues/1341
> Add recent REPL results globals *i and most recent error *e

- NEWS.rst
- hy/lex/parser.py
- tests/test_lex.py
Fixes https://github.com/hylang/hy/issues/1571
> Raise LexException when codec can't decode some bytes

- NEWS.rst
- hy/compiler.py
- hy/core/bootstrap.hy
- hy/core/language.hy
- hy/macros.py
- tests/macros/test_macro_processor.py
- tests/native_tests/quote.hy
> Fix bug in macro-expanding NaN

- NEWS.rst
- hy/compiler.py
- tests/compilers/test_ast.py
> Fix a bug where the compiler doesn't properly handle unquote-splice

- NEWS.rst
- hy/compiler.py
- hy/contrib/walk.hy
- tests/compilers/test_ast.py
- tests/native_tests/language.hy
> Remove tuple unpacking in lambda lists

- NEWS.rst
- docs/language/index.rst
- docs/language/model_patterns.rst
- tests/native_tests/model_patterns.hy
> Add tests and docs for model patterns

- hy/compiler.py
- setup.cfg
- tests/native_tests/language.hy
- tests/native_tests/native_macros.hy
> Miscellaneous small changes

- NEWS.rst
- docs/language/api.rst
- docs/language/syntax.rst
- Closes #1402.
- Closes #1620.
- Closes #1632
- Closes #1640.
> Small documentation additions

- NEWS.rst
- hy/compiler.py
- tests/compilers/test_ast.py
- tests/native_tests/language.hy
> Make empty expressions illegal at the top level

- NEWS.rst
- docs/language/api.rst
- hy/compiler.py
- hy/model_patterns.py
- tests/compilers/test_ast.py
> Fix handling of unpacking in method calls and attribute lookups

- hy/__init__.py
- hy/cmdline.py
- hy/compiler.py
- hy/core/language.hy
- hy/core/macros.hy
- hy/core/shadow.hy
- hy/importer.py
- hy/lex/__init__.py
- tests/compilers/test_ast.py
- tests/importer/test_importer.py
- tests/native_tests/native_macros.hy
- tests/test_lex.py
This PR performs some of the clean-up/reorganizing discussed in the following issues:
> Reorganize utility functions and imports

- NEWS.rst
- hy/core/macros.hy
- tests/native_tests/native_macros.hy
> Make `defmain` args optional or variadic when empty

- NEWS.rst
- hy/lex/__init__.py
- tests/native_tests/mangling.hy
> Fix mangling of characters below 0xFF

- docs/language/interop.rst
> Fix an example in interop.rst

- docs/style-guide.rst
> Correct documentation of earmuff behavior

- docs/tutorial.rst
This change adds to the tutorial the hy way of indexing array.
> Add array indexes cut tutorial

- hy/core/macros.hy
> Check arguments in with-decorator tag

- AUTHORS
- NEWS.rst
- docs/language/core.rst
- hy/contrib/hy_repr.hy
- hy/contrib/walk.hy
- hy/core/language.hy
- hy/core/macros.hy
- tests/native_tests/core.hy
`expression?` will test if the input is an instance of HyExpression.
> add `list?` function to `hy.core`

- NEWS.rst
- docs/language/core.rst
- hy/core/language.hy
- tests/native_tests/core.hy
`tuple?` will test if the argument is an instance of tuple.
> add `tuple?` function `hy.core`

- NEWS.rst
- docs/language/api.rst
- hy/core/language.hy
- tests/native_tests/core.hy
- tests/native_tests/native_macros.hy
Closes #1531.
I use @gilch's idea from #1651.
> Simplify gensym format

- tests/importer/test_importer.py
- tests/resources/hello_world.hy
>  Add a test for a previously fixed reloading bug

- NEWS.rst
- docs/contrib/hy_repr.rst
- docs/language/api.rst
- docs/tutorial.rst
- hy/compiler.py
- hy/contrib/multi.hy
- hy/contrib/sequences.hy
- tests/native_tests/contrib/hy_repr.hy
- tests/native_tests/core.hy
- tests/native_tests/defclass.hy
- tests/native_tests/language.hy
- tests/native_tests/mathematics.hy
- tests/native_tests/operators.hy
- tests/native_tests/py36_only_tests.hy
- tests/native_tests/with_decorator.hy
- tests/resources/pydemo.hy
- tests/test_hy2py.py
> Remove the attribute list of `defclass`

- docs/language/api.rst
> Document `await`

- NEWS.rst
- hy/compiler.py
- tests/native_tests/language.hy
>  Run statements in the second argument of `assert`

- NEWS.rst
- hy/compiler.py
- tests/resources/pydemo.hy
- tests/test_hy2py.py
> Fix AST representation of format strings

- NEWS.rst
- docs/language/api.rst
- docs/language/interop.rst
- docs/whyhy.rst
- hy/compiler.py
- tests/compilers/test_ast.py
- tests/resources/pydemo.hy
- tests/test_hy2py.py
I would've sworn that we had an issue requesting this feature, but I can't find it.
> Allow inline Python 

- AUTHORS
- NEWS.rst
- docs/language/core.rst
- hy/core/language.hy
- tests/native_tests/core.hy
I went through the steps in `CONTRIBUTING`, but please let me know if any changes are required.
Thanks for your work on Hy.
> Add: parse-args function

- docs/contrib/walk.rst
> Document gotcha with unintentional recursion in `let`

- NEWS.rst
- hy/extra/anaphoric.hy
- tests/native_tests/extra/anaphoric.hy
Fixes #1848, and also an unreported multiple-evaluation bug.
> Fix some bugs in `ap-reduce`

- docs/extra/anaphoric.rst
- hy/extra/anaphoric.hy
- tests/native_tests/extra/anaphoric.hy
- tests/native_tests/extra/anaphoric_single.hy
- Fixes #1847.
- Fixes #1853.
@falloutphil, would you care to stress-test this?
> Overhaul hy.extra.anaphoric

- NEWS.rst
- docs/language/api.rst
- hy/compiler.py
- hy/core/shadow.hy
- tests/native_tests/operators.hy
> Implement chained comparisons

- NEWS.rst
- hy/compiler.py
- tests/native_tests/language.hy
> Avoid evaluating quoted f-strings

- NEWS.rst
- hy/cmdline.py
- tests/test_bin.py
> Fix scoping bug in `hy -c`

- NEWS.rst
- hy/compiler.py
- tests/compilers/test_ast.py
> Fix `require` with multiple arguments

- NEWS.rst
- hy/cmdline.py
- tests/native_tests/language.hy
- tests/resources/bin/main.hy
- tests/test_bin.py
> Rewrite option parsing in `cmdline_handler`

- tests/native_tests/core.hy
> In `test-doc`, use a purpose-written macro

- README.md
> Link to the new Hy web console from the README

- AUTHORS
Updating from old email address to new one.
> Update email address

- tox.ini
This doesn't fix any of the flake8 issues, but those will likely require more systemic changes. Closes #1962
> Fix: bring tox up to date

- docs/api.rst
- docs/cheatsheet.json
> Docs: missing special forms

- tests/native_tests/language.hy
> Fix: test eval can see locals

- tests/native_tests/tag_macros.hy
> Fix: Add test for empty decorator call

- docs/style-guide.rst
Sorry about the pull-request mistake the first time.
> Fix spelling mistake in style-guide

- NEWS.rst
- docs/api.rst
- hy/compiler.py
- tests/native_tests/language.hy
all hail special forms :pray:
closes  #2017
> Feature: move defn return annotation to before func name

- NEWS.rst
- hy/compiler.py
- tests/native_tests/defclass.hy
closes #1544 
no magic allowed :no_entry_sign:  :mage_man: :no_entry_sign:
> Fix: Remove __init__ suppression automagic

- hy/compiler.py
- hy/macros.py
- tests/native_tests/contrib/walk.hy
- tests/native_tests/language.hy
- tests/native_tests/operators.hy
No user-visible changes. These are some commits I made while working on #2046.
> Miscellaneous cleanup

- docs/index.rst
Removed unnecessary quotes which were breaking the link
> Fixed discussions link

- hy/macros.py
> Fix macro code object modification for python 3.10.0rc2

- setup.py
> Add: project_urls to package info

- conftest.py
> Remove py monkeypatching from conftest

- docs/tutorial.rst
There remains work to be done, but I want to put this aside for the moment, so I've committed what I did so far.
> Fix some Sphinx links

- NEWS.rst
- hy/completer.py
- tests/test_completer.py
> Delay the import of Readline

- hy/pyops.hy
I'm not sure whether it makes sense to list the binary and three-or-more-ary cases separately, since the binary case always work the same as the n-ary case when it exists, but it may be easier to digest this way.
> Provide more complete docstrings for Python ops

- NEWS.rst
- docs/language/internals.rst
- docs/tutorial.rst
- hy/core/hy_repr.hy
- hy/core/macros.hy
- tests/native_tests/language.hy
- tests/native_tests/model_patterns.hy
- tests/native_tests/native_macros.hy
- tests/native_tests/when.hy
- tests/resources/argparse_ex.hy
> Unbracketed `cond`

- NEWS.rst
- docs/api.rst
- hy/core/hy_repr.hy
- hy/core/macros.hy
- hy/core/result_macros.py
- hy/reserved.hy
- tests/compilers/test_ast.py
- tests/native_tests/comprehensions.hy
- tests/native_tests/language.hy
- tests/native_tests/let.hy
- tests/native_tests/model_patterns.hy
- tests/native_tests/operators.hy
- tests/test_bin.py
> Make `if` require three arguments

- .github/workflows/tests.yml
- tests/compilers/test_ast.py
> Add an xfail test for newline styles in string literals

- NEWS.rst
- hy/completer.py
- tests/test_completer.py
This was really getting under my skin.
> Fix completion not unmangling names

- .pre-commit-config.yaml
- NEWS.rst
- docs/language/syntax.rst
- hy/_compat.py
- hy/compiler.py
- hy/core/result_macros.py
- hy/lex/__init__.py
- hy/lex/lexer.py
- requirements-dev.txt
- tests/native_tests/language.hy
- tests/native_tests/mangling.hy
- tests/resources/pydemo.hy
- tests/test_hy2py.py
- Closes #2216.
- Undoes #2081.
I haven't yet added NEWS or documentation, in case there's disagreement about the details.
> Account for Python's Unicode normalization

- NEWS.rst
- hy/cmdline.py
- tests/test_bin.py
> Refinement of command-line options

- CONTRIBUTING.rst
- docs/language/internals.rst
- docs/tutorial.rst
- docs/whyhy.rst
- Closes #1490.
- Closes #1592.
- Closes #1596.
If there are no objections, I'll delete the label "good first issue" once this is merged.
> Documentation tweaks

- NEWS.rst
- docs/language/syntax.rst
- hy/lex/hy_reader.py
- tests/compilers/test_ast.py
- tests/test_lex.py
- Closes #1227.
- Closes #2239.
- Closes #2254.
> Small parser improvements

- NEWS.rst
- docs/language/syntax.rst
- hy/compiler.py
- tests/native_tests/language.hy
> Add `...` as special syntax for Ellipsis

- docs/api.rst
- docs/syntax.rst
- hy/models.py
> Rewrite and expand the syntax documentation

- NEWS.rst
- docs/api.rst
- hy/core/macros.hy
- hy/core/result_macros.py
- hy/lex/hy_reader.py
- tests/native_tests/language.hy
- tests/native_tests/py3_10_only_tests.hy
- tests/native_tests/reader_macros.hy
- tests/resources/pydemo.hy
> #^ annotations

- docs/syntax.rst
- docs/tutorial.rst
- hy/models.py
Closes #1796 (in combination with #2279).
> Documentation refinements

- docs/index.rst
- docs/semantics.rst
- docs/tutorial.rst
> Document more gotchas

- setup.py
To let https://github.com/hylang/hyrule/pull/46 work.
> Add "wheel" to `setup_requires`

- NEWS.rst
- hy/cmdline.py
- tests/test_bin.py
> Set `__file__` the same way as in Python

- NEWS.rst
- hy/core/result_macros.py
- tests/native_tests/language.hy
- tests/test_bin.py
> Fix a statement-moving bug in `assert`

- NEWS.rst
- docs/api.rst
- hy/core/result_macros.py
- hy/pyops.hy
- tests/native_tests/comprehensions.hy
- tests/resources/pydemo.hy
> Remove final brackets from `dfor`

- NEWS.rst
- conftest.py
- docs/api.rst
- hy/core/result_macros.py
- tests/compilers/test_ast.py
- tests/native_tests/py3_11_only_tests.hy
> Support `except*` in `try`

- docs/interop.rst
> Document strategies for Python libraries

- .github/workflows/tests.yml
- docs/api.rst
- docs/cli.rst
- docs/model_patterns.rst
- hy/core/hy_repr.hy
- hy/core/util.hy
- tests/native_tests/hy_repr.hy
- tests/resources/hy_repr_str_tests.txt
> Miscellaneous testing and documentation improvements

- NEWS.rst
- docs/api.rst
- hy/core/result_macros.py
- tests/compilers/test_ast.py
> Release Hy 0.25.0

- hy/pyops.hy
- requirements-dev.txt
> Documentation fixes

- NEWS.rst
- docs/api.rst
- docs/syntax.rst
- hy/core/hy_repr.hy
- hy/core/result_macros.py
- hy/pyops.hy
- hy/reader/hy_reader.py
- tests/compilers/test_ast.py
- tests/native_tests/operators.hy
- tests/resources/hy_repr_str_tests.txt
- tests/test_reader.py
> Smooth out warts in the parsing of quote constructs

- LICENSE
- NEWS.rst
- docs/api.rst
- docs/syntax.rst
- hy/compiler.py
- hy/core/hy_repr.hy
- hy/core/result_macros.py
- hy/macros.py
- hy/models.py
- hy/reader/hy_reader.py
- hy/reader/mangling.py
- tests/compilers/test_ast.py
- tests/native_tests/language.hy
- tests/native_tests/native_macros.hy
- tests/resources/__init__.py
- tests/resources/hy_repr_str_tests.txt
- tests/test_reader.py
> Parse dotted identifiers as expressions

- README.md
- docs/index.rst
- docs/whyhy.rst
- hy/repl.py
- setup.py
See https://github.com/hylang/hyhomepage
> Changes to support the new Pyodide-based Try Hy

- NEWS.rst
- docs/api.rst
- docs/env_var.rst
- docs/syntax.rst
- hy/errors.py
- hy/models.py
- hy/repl.py
- setup.py
- tests/test_models.py
> Remove color

- docs/api.rst
- hy/core/result_macros.py
- tests/native_tests/match.hy
> Fix `match` patterns with a dotted constructor

- NEWS.rst
- docs/api.rst
- hy/compiler.py
- hy/completer.py
- hy/core/macros.hy
- hy/core/result_macros.py
- hy/macros.py
- hy/repl.py
- hy/reserved.hy
- tests/compilers/test_ast.py
- tests/native_tests/import.hy
- tests/native_tests/reader_macros.hy
- Closes #2386
- Closes #2406
- Closes #2410
> Miscellany

- NEWS.rst
- hy/reader/__init__.py
- hy/reader/hy_reader.py
- tests/test_bin.py
- tests/test_reader.py
> Skip shebangs in the reader, not outside it

- NEWS.rst
- hy/reader/hy_reader.py
- tests/test_reader.py
> Recurse in `HyReader.fill_pos`

- .github/workflows/tests.yml
- NEWS.rst
- docs/api.rst
- docs/conf.py
- hy/__init__.py
- tests/native_tests/hy_misc.hy
- Closes #2416 
I intend no prejudice against a reader macro as proposed by @scauligi in the linked issue, but it would need to expand to something, and I propose this as what it would expand to if we had it.
> Add `hy.M` import sugar

- .github/workflows/tests.yml
- tests/test_bin.py
- tests/test_completer.py
im on a mac now and the tests wernt working so i fixed them
> Fix tests for MacOS (and also for running locally)

- NEWS.rst
- docs/api.rst
- hy/pyops.hy
- tests/native_tests/cut.hy
- tests/native_tests/operators.hy
> Add a function version of `cut`

- hy/_compat.py
- hy/core/result_macros.py
wow there are a lot of new deprecation warnings in 3.12
not looking forward to that
> Deal with new Python 3.12 AST changes

- NEWS.rst
- docs/syntax.rst
- hy/pyops.hy
- hy/reader/mangling.py
- tests/native_tests/mangling.hy
> Don't mangle question marks specially

- NEWS.rst
- docs/api.rst
- hy/core/result_macros.py
- setup.cfg
- tests/compilers/test_ast.py
- tests/native_tests/try.hy
- tests/test_hy2py.py
The most interesting, user-visible commit is the last one. The others are just various kinds of testing improvements.
> `try` cleanup

- NEWS.rst
- hy/core/result_macros.py
- hy/macros.py
- hy/model_patterns.py
- tests/compilers/test_ast.py
- Closes #2415
More improvements could probably be made, but I think this is enough for the time being.
> Improve model-pattern error msgs for core macros

- docs/api.rst
- hy/core/macros.hy
> Improve docs for reader macros

- hy/core/macros.hy
- hy/core/result_macros.py
- hy/macros.py
- tests/macros/test_macro_processor.py
- tests/native_tests/hy_eval.hy
- tests/native_tests/hy_misc.hy
- tests/native_tests/macros_first_class.hy
- Closes #1455 (this is now a wholly internal matter, so it doesn't need to be documented)
> Make the magic parameter of macros optional

- LICENSE
- NEWS.rst
Predictably, I didn't do anything on Hy after switching focus to Infinitesimal Quest 2 + ε in early December. I probably should've just made the release then.
> Release Hy 0.28.0

- NEWS.rst
- docs/repl.rst
- hy/repl.py
- tests/resources/hystartup.hy
- tests/test_bin.py
> Add `HYSTARTUP` variables for prompt strings 

- NEWS.rst
- docs/semantics.rst
- hy/compiler.py
- hy/core/result_macros.py
- hy/models.py
- tests/test_positions.py
> Fix some traceback positions

- AUTHORS
If there are no objections, I'll make the same changes to Hyrule.
> Clean up AUTHORS

- .github/workflows/tests.yml
- docs/api.rst
- docs/conf.py
- docs/model_patterns.rst
- hy/core/util.hy
- requirements-dev.txt
I also added a GitHub Action check that there are no warnings, so we should be able to see regressions.
> Silence Sphinx warnings

- NEWS.rst
- docs/syntax.rst
- hy/models.py
- tests/native_tests/keywords.hy
> Make keyword objects comparable

- NEWS.rst
- docs/macros.rst
- hy/repl.py
- tests/native_tests/repl.hy
> Replace `_hy_maybe_compile` with a one-liner

- NEWS.rst
- hy/macros.py
- tests/native_tests/dots.hy
> Fix the handling of dot expressions with ""

- docs/syntax.rst
- tests/importer/test_importer.py
- tests/native_tests/keywords.hy
- tests/resources/__init__.py
> Correct the docs on the parsing of keywords

- NEWS.rst
- hy/core/result_macros.py
- tests/native_tests/logic_short_circuit.hy
Fixes #2640.
Derp. Simple enough fix.
> Fix logical ops failing to compile non-expression statements

- .github/workflows/tests.yaml
- CONTRIBUTING.rst
- docs/requirements.txt
> Require a newer pytest
